fishes = [
{'available': False, 'name': 'Strip of Malm Kelp', 'max': 8.9, 'index': 0, 'url': ''},
{'available': False, 'name': 'Crayfish', 'max': 6.9, 'index': 1, 'url': ''},
{'available': False, 'name': 'Chub', 'max': 8.9, 'index': 2, 'url': ''},
{'available': False, 'name': 'Merlthor Goby', 'max': 9.3, 'index': 3, 'url': ''},
{'available': True, 'name': 'Lominsan Anchovy', 'max': 8.1, 'index': 4, 'url': ''},
{'available': True, 'name': 'Striped Goby', 'max': 7.3, 'index': 5, 'url': ''},
{'available': True, 'name': 'Dwarf Catfish', 'max': 9.3, 'index': 6, 'url': ''},
{'available': False, 'name': 'Finger Shrimp', 'max': 8.5, 'index': 7, 'url': ''},
{'available': False, 'name': 'Bone Crayfish', 'max': 8.5, 'index': 8, 'url': ''},
{'available': False, 'name': 'Piece of White Coral', 'max': 9.7, 'index': 9, 'url': ''},
{'available': False, 'name': 'Princess Trout', 'max': 9.7, 'index': 10, 'url': ''},
{'available': False, 'name': 'Ocean Cloud', 'max': 10.9, 'index': 11, 'url': ''},
{'available': False, 'name': 'Dusk Goby', 'max': 8.1, 'index': 12, 'url': ''},
{'available': False, 'name': 'Sea Cucumber', 'max': 9.3, 'index': 13, 'url': ''},
{'available': False, 'name': 'Harbor Herring', 'max': 12.8, 'index': 14, 'url': ''},
{'available': False, 'name': 'Pipira', 'max': 10.5, 'index': 15, 'url': ''},
{'available': False, 'name': 'Crimson Crayfish', 'max': 10.1, 'index': 16, 'url': ''},
{'available': True, 'name': 'Vongola Clam', 'max': 6.9, 'index': 17, 'url': ''},
{'available': True, 'name': 'Gudgeon', 'max': 9.7, 'index': 18, 'url': ''},
{'available': False, 'name': 'Coral Butterfly', 'max': 13.2, 'index': 19, 'url': ''},
{'available': False, 'name': 'Brass Loach', 'max': 8.9, 'index': 20, 'url': ''},
{'available': True, 'name': 'Moraby Flounder', 'max': 16.3, 'index': 21, 'url': ''},
{'available': True, 'name': 'Maiden Carp', 'max': 11.7, 'index': 22, 'url': ''},
{'available': False, 'name': 'Abalathian Smelt', 'max': 5.8, 'index': 23, 'url': ''},
{'available': False, 'name': 'Blindfish', 'max': 8.1, 'index': 24, 'url': ''},
{'available': False, 'name': 'Pebble Crab', 'max': 12.4, 'index': 25, 'url': ''},
{'available': True, 'name': 'Mudskipper', 'max': 11.3, 'index': 26, 'url': ''},
{'available': True, 'name': 'Rainbow Trout', 'max': 15.6, 'index': 27, 'url': ''},
{'available': True, 'name': 'River Crab', 'max': 9.7, 'index': 28, 'url': ''},
{'available': True, 'name': 'Tiger Cod', 'max': 16.0, 'index': 29, 'url': ''},
{'available': True, 'name': 'Ala Mhigan Fighting Fish', 'max': 10.9, 'index': 30, 'url': ''},
{'available': True, 'name': 'Helmet Crab', 'max': 17.2, 'index': 31, 'url': ''},
{'available': False, 'name': 'Faerie Bass', 'max': 17.6, 'index': 32, 'url': ''},
{'available': True, 'name': 'Acorn Snail', 'max': 6.9, 'index': 33, 'url': ''},
{'available': True, 'name': 'Rothlyt Oyster', 'max': 9.7, 'index': 34, 'url': ''},
{'available': False, 'name': 'Dark Sleeper', 'max': 11.3, 'index': 35, 'url': ''},
{'available': True, 'name': 'La Noscean Perch', 'max': 18.4, 'index': 36, 'url': ''},
{'available': True, 'name': "Navigator's Dagger", 'max': 23.5, 'index': 37, 'url': ''},
{'available': True, 'name': 'Moat Carp', 'max': 13.2, 'index': 38, 'url': ''},
{'available': True, 'name': 'Angelfish', 'max': 30.2, 'index': 39, 'url': ''},
{'available': True, 'name': 'Copperfish', 'max': 11.7, 'index': 40, 'url': ''},
{'available': False, 'name': 'Bluebell Salmon', 'max': 17.6, 'index': 41, 'url': ''},
{'available': True, 'name': 'Razor Clam', 'max': 12.4, 'index': 42, 'url': ''},
{'available': True, 'name': 'Mudcrab', 'max': 12.4, 'index': 43, 'url': ''},
{'available': True, 'name': 'Blue Octopus', 'max': 37.6, 'index': 44, 'url': ''},
{'available': False, 'name': 'Tri-Colored Carp', 'max': 22.7, 'index': 45, 'url': ''},
{'available': True, 'name': 'Eunuch Crayfish', 'max': 17.6, 'index': 46, 'url': ''},
{'available': True, 'name': 'Jade Eel', 'max': 25.0, 'index': 47, 'url': ''},
{'available': False, 'name': 'Blowfish', 'max': 21.5, 'index': 48, 'url': ''},
{'available': False, 'name': 'Pond Mussel', 'max': 9.7, 'index': 49, 'url': ''},
{'available': False, 'name': 'Warmwater Trout', 'max': 21.1, 'index': 50, 'url': ''},
{'available': True, 'name': 'Glass Perch', 'max': 24.7, 'index': 51, 'url': ''},
{'available': True, 'name': 'Four-Eyed Fish', 'max': 18.0, 'index': 52, 'url': ''},
{'available': False, 'name': 'Saber Sardine', 'max': 31.7, 'index': 53, 'url': ''},
{'available': False, 'name': 'Black Eel', 'max': 25.4, 'index': 54, 'url': ''},
{'available': False, 'name': 'Dark Bass', 'max': 27.4, 'index': 55, 'url': ''},
{'available': True, 'name': 'Piece of Blue Coral', 'max': 25.0, 'index': 56, 'url': ''},
{'available': False, 'name': 'Ogre Barracuda', 'max': 47.9, 'index': 57, 'url': ''},
{'available': False, 'name': 'Aegis Shrimp', 'max': 3.8, 'index': 58, 'url': ''},
{'available': False, 'name': 'Five-Ilm Pleco', 'max': 7.7, 'index': 59, 'url': ''},
{'available': False, 'name': 'Monkfish', 'max': 58.5, 'index': 60, 'url': ''},
{'available': True, 'name': 'Sea Bo', 'max': 20.7, 'index': 61, 'url': ''},
{'available': True, 'name': 'Climbing Perch', 'max': 17.2, 'index': 62, 'url': ''},
{'available': True, 'name': 'Shadow Catfish', 'max': 30.6, 'index': 63, 'url': ''},
{'available': True, 'name': 'Bianaq Bream', 'max': 52.6, 'index': 64, 'url': ''},
{'available': True, 'name': 'Black Ghost', 'max': 29.4, 'index': 65, 'url': ''},
{'available': False, 'name': 'Black Sole', 'max': 32.5, 'index': 66, 'url': ''},
{'available': True, 'name': 'Lamprey', 'max': 28.6, 'index': 67, 'url': ''},
{'available': True, 'name': 'Plaguefish', 'max': 16.8, 'index': 68, 'url': ''},
{'available': False, 'name': 'Hammerhead Shark', 'max': 58.9, 'index': 69, 'url': ''},
{'available': True, 'name': "Yugr'am Salmon", 'max': 31.0, 'index': 70, 'url': ''},
{'available': False, 'name': 'Sea Pickle', 'max': 33.3, 'index': 71, 'url': ''},
{'available': False, 'name': 'Spotted Pleco', 'max': 29.0, 'index': 72, 'url': ''},
{'available': False, 'name': 'Lamp Marimo', 'max': 10.1, 'index': 73, 'url': ''},
{'available': False, 'name': 'Indigo Herring', 'max': 43.2, 'index': 74, 'url': ''},
{'available': False, 'name': 'Ropefish', 'max': 38.0, 'index': 75, 'url': ''},
{'available': False, 'name': 'Ash Tuna', 'max': 69.1, 'index': 76, 'url': ''},
{'available': False, 'name': 'Grip Killifish', 'max': 8.9, 'index': 77, 'url': ''},
{'available': True, 'name': 'Bone Cleaner', 'max': 15.2, 'index': 78, 'url': ''},
{'available': True, 'name': 'Root Skipper', 'max': 10.9, 'index': 79, 'url': ''},
{'available': False, 'name': 'Leafy Seadragon', 'max': 34.5, 'index': 80, 'url': ''},
{'available': True, 'name': 'Bonytongue', 'max': 41.2, 'index': 81, 'url': ''},
{'available': False, 'name': 'Fullmoon Sardine', 'max': 21.5, 'index': 82, 'url': ''},
{'available': False, 'name': 'Mitten Crab', 'max': 21.9, 'index': 83, 'url': ''},
{'available': True, 'name': 'Haraldr Haddock', 'max': 53.0, 'index': 84, 'url': ''},
{'available': False, 'name': 'Monke Onke', 'max': 37.3, 'index': 85, 'url': ''},
{'available': True, 'name': 'Seema', 'max': 36.9, 'index': 86, 'url': ''},
{'available': False, 'name': 'Whitelip Oyster', 'max': 17.6, 'index': 87, 'url': ''},
{'available': True, 'name': 'Sandfish', 'max': 13.2, 'index': 88, 'url': ''},
{'available': False, 'name': 'Silverfish', 'max': 16.4, 'index': 89, 'url': ''},
{'available': True, 'name': 'Clown Loach', 'max': 34.1, 'index': 90, 'url': ''},
{'available': False, 'name': 'Sand Bream', 'max': 21.9, 'index': 91, 'url': ''},
{'available': False, 'name': 'Lavender Remora', 'max': 60.9, 'index': 92, 'url': ''},
{'available': True, 'name': 'Armored Pleco', 'max': 36.9, 'index': 93, 'url': ''},
{'available': True, 'name': 'Giant Bass', 'max': 43.2, 'index': 94, 'url': ''},
{'available': False, 'name': 'Desert Catfish', 'max': 31.3, 'index': 95, 'url': ''},
{'available': False, 'name': 'Balloonfish', 'max': 48.7, 'index': 96, 'url': ''},
{'available': True, 'name': 'Velodyna Carp', 'max': 40.4, 'index': 97, 'url': ''},
{'available': False, 'name': 'Spotted Puffer', 'max': 5.8, 'index': 98, 'url': ''},
{'available': True, 'name': 'Dustfish', 'max': 28.2, 'index': 99, 'url': ''},
{'available': True, 'name': 'Golden Loach', 'max': 41.6, 'index': 100, 'url': ''},
{'available': True, 'name': 'Storm Rider', 'max': 17.6, 'index': 101, 'url': ''},
{'available': False, 'name': 'Trader Eel', 'max': 41.2, 'index': 102, 'url': ''},
{'available': False, 'name': 'Crimson Trout', 'max': 38.0, 'index': 103, 'url': ''},
{'available': True, 'name': 'Discus', 'max': 34.5, 'index': 104, 'url': ''},
{'available': True, 'name': 'Antlion Slug', 'max': 23.5, 'index': 105, 'url': ''},
{'available': True, 'name': 'Piece of Red Coral', 'max': 35.3, 'index': 106, 'url': ''},
{'available': True, 'name': 'Bronze Lake Trout', 'max': 48.7, 'index': 107, 'url': ''},
{'available': True, 'name': 'Ignus Snail', 'max': 5.8, 'index': 108, 'url': ''},
{'available': False, 'name': 'Dune Manta', 'max': 55.0, 'index': 109, 'url': ''},
{'available': False, 'name': 'Silver Shark', 'max': 82.5, 'index': 110, 'url': ''},
{'available': True, 'name': 'Loyal Pleco', 'max': 46.3, 'index': 111, 'url': ''},
{'available': True, 'name': 'Thunderbolt Sculpin', 'max': 37.3, 'index': 112, 'url': ''},
{'available': True, 'name': 'Fall Jumper', 'max': 40.4, 'index': 113, 'url': ''},
{'available': False, 'name': 'Knifefish', 'max': 43.6, 'index': 114, 'url': ''},
{'available': True, 'name': 'Wahoo', 'max': 60.9, 'index': 115, 'url': ''},
{'available': True, 'name': 'Raincaller', 'max': 45.1, 'index': 116, 'url': ''},
{'available': True, 'name': 'Oakroot', 'max': 47.1, 'index': 117, 'url': ''},
{'available': True, 'name': 'Common Sculpin', 'max': 17.6, 'index': 118, 'url': ''},
{'available': False, 'name': 'Blacklip Oyster', 'max': 21.5, 'index': 119, 'url': ''},
{'available': True, 'name': 'Southern Pike', 'max': 46.3, 'index': 120, 'url': ''},
{'available': False, 'name': 'Northern Pike', 'max': 46.3, 'index': 121, 'url': ''},
{'available': True, 'name': 'Kobold Puffer', 'max': 6.9, 'index': 122, 'url': ''},
{'available': False, 'name': 'Nautilus', 'max': 55.0, 'index': 123, 'url': ''},
{'available': True, 'name': 'Archerfish', 'max': 26.6, 'index': 124, 'url': ''},
{'available': False, 'name': 'Cloud Jellyfish', 'max': 17.6, 'index': 125, 'url': ''},
{'available': True, 'name': 'Goblin Perch', 'max': 48.3, 'index': 126, 'url': ''},
{'available': True, 'name': 'Agelyss Carp', 'max': 51.4, 'index': 127, 'url': ''},
{'available': False, 'name': 'Pike Eel', 'max': 79.0, 'index': 128, 'url': ''},
{'available': False, 'name': 'Assassin Betta', 'max': 12.8, 'index': 129, 'url': ''},
{'available': True, 'name': 'Sludgeskipper', 'max': 12.1, 'index': 130, 'url': ''},
{'available': False, 'name': 'Skyfish', 'max': 21.9, 'index': 131, 'url': ''},
{'available': True, 'name': 'Mummer Wrasse', 'max': 95.9, 'index': 132, 'url': ''},
{'available': True, 'name': 'Cloud Cutter', 'max': 28.6, 'index': 133, 'url': ''},
{'available': True, 'name': 'Boltfish', 'max': 53.0, 'index': 134, 'url': ''},
{'available': True, 'name': 'Garpike', 'max': 58.9, 'index': 135, 'url': ''},
{'available': True, 'name': 'Blind Manta', 'max': 58.9, 'index': 136, 'url': ''},
{'available': True, 'name': 'Plaice', 'max': 62.8, 'index': 137, 'url': ''},
{'available': False, 'name': 'Ilsabardian Bass', 'max': 60.9, 'index': 138, 'url': ''},
{'available': False, 'name': "Paglth'an Discus", 'max': 42.8, 'index': 139, 'url': ''},
{'available': False, 'name': 'Boxing Pleco', 'max': 45.5, 'index': 140, 'url': ''},
{'available': True, 'name': 'Rift Sailor', 'max': 27.4, 'index': 141, 'url': ''},
{'available': False, 'name': 'Sea Devil', 'max': 60.9, 'index': 142, 'url': ''},
{'available': False, 'name': 'Kissing Trout', 'max': 49.5, 'index': 143, 'url': ''},
{'available': False, 'name': 'Angry Pike', 'max': 54.2, 'index': 144, 'url': ''},
{'available': False, 'name': 'Goldfish', 'max': 21.1, 'index': 145, 'url': ''},
{'available': False, 'name': 'Sagolii Monkfish', 'max': 78.6, 'index': 146, 'url': ''},
{'available': True, 'name': 'Saucerfish', 'max': 58.9, 'index': 147, 'url': ''},
{'available': False, 'name': 'Rock Lobster', 'max': 31.3, 'index': 148, 'url': ''},
{'available': False, 'name': 'Vampire Lampern', 'max': 53.0, 'index': 149, 'url': ''},
{'available': True, 'name': 'Wandering Sculpin', 'max': 42.8, 'index': 150, 'url': ''},
{'available': False, 'name': 'Goosefish', 'max': 97.5, 'index': 151, 'url': ''},
{'available': False, 'name': 'Cave Cherax', 'max': 32.9, 'index': 152, 'url': ''},
{'available': True, 'name': 'Coeurlfish', 'max': 82.5, 'index': 153, 'url': ''},
{'available': True, 'name': 'Little Thalaos', 'max': 118.0, 'index': 154, 'url': ''},
{'available': True, 'name': 'Shall Shell', 'max': 82.5, 'index': 155, 'url': ''},
{'available': False, 'name': 'Giant Donko', 'max': 57.7, 'index': 156, 'url': ''},
{'available': False, 'name': 'Sundisc', 'max': 51.0, 'index': 157, 'url': ''},
{'available': False, 'name': 'Mahi-Mahi', 'max': 97.5, 'index': 158, 'url': ''},
{'available': True, 'name': 'Halibut', 'max': 100.2, 'index': 159, 'url': ''},
{'available': True, 'name': 'Alligator Garfish', 'max': 65.6, 'index': 160, 'url': ''},
{'available': False, 'name': 'Wootz Knifefish', 'max': 60.1, 'index': 161, 'url': ''},
{'available': True, 'name': 'Giant Catfish', 'max': 70.3, 'index': 162, 'url': ''},
{'available': False, 'name': 'Caravan Eel', 'max': 86.5, 'index': 163, 'url': ''},
{'available': False, 'name': 'Mazlaya Marlin', 'max': 114.0, 'index': 164, 'url': ''},
{'available': True, 'name': 'Coelacanth', 'max': 80.6, 'index': 165, 'url': ''},
{'available': True, 'name': 'Cadaver Carp', 'max': 77.4, 'index': 166, 'url': ''},
{'available': True, 'name': 'Rhamphorhynchus', 'max': 149.4, 'index': 167, 'url': ''},
{'available': True, 'name': 'Giant Squid', 'max': 117.6, 'index': 168, 'url': ''},
{'available': True, 'name': 'Gigant Octopus', 'max': 149.5, 'index': 169, 'url': ''},
{'available': False, 'name': 'Sunfish', 'max': 97.9, 'index': 170, 'url': ''},
{'available': False, 'name': 'Dinichthys', 'max': 165.2, 'index': 171, 'url': ''},
{'available': False, 'name': 'Mushroom Crab', 'max': 25.4, 'index': 172, 'url': ''},
{'available': True, 'name': 'Judgment Staff', 'max': 53.0, 'index': 173, 'url': ''},
{'available': False, 'name': 'Poxpike', 'max': 70.7, 'index': 174, 'url': ''},
{'available': True, 'name': 'Emperor Fish', 'max': 60.9, 'index': 175, 'url': ''},
{'available': True, 'name': 'Bowfin', 'max': 56.9, 'index': 176, 'url': ''},
{'available': True, 'name': 'Heliobatis', 'max': 87.1, 'index': 177, 'url': ''},
{'available': True, 'name': 'Megalodon', 'max': 181.0, 'index': 178, 'url': ''},
{'available': False, 'name': 'Titanic Sawfish', 'max': 196.2, 'index': 179, 'url': ''},
{'available': True, 'name': 'Takitaro', 'max': 94.3, 'index': 180, 'url': ''},
{'available': False, 'name': 'Pirarucu', 'max': 106.1, 'index': 181, 'url': ''},
{'available': True, 'name': 'Morinabaligi', 'max': 94.3, 'index': 182, 'url': ''},
{'available': True, 'name': 'Jungle Catfish', 'max': 62.4, 'index': 183, 'url': ''},
{'available': True, 'name': 'Tiny Tortoise', 'max': 25.6, 'index': 184, 'url': ''},
{'available': False, 'name': 'Gigantpole', 'max': 25.6, 'index': 185, 'url': ''},
{'available': True, 'name': 'Zalera', 'max': 45.3, 'index': 186, 'url': ''},
{'available': False, 'name': 'Beguiler Chub', 'max': 13.4, 'index': 187, 'url': ''},
{'available': True, 'name': "Oschon's Print", 'max': 20.5, 'index': 188, 'url': ''},
{'available': True, 'name': 'Caterwauler', 'max': 14.0, 'index': 189, 'url': ''},
{'available': False, 'name': 'Crystal Perch', 'max': 37.1, 'index': 190, 'url': ''},
{'available': True, 'name': 'Moldva', 'max': 16.4, 'index': 191, 'url': ''},
{'available': True, 'name': 'Junkmonger', 'max': 146.3, 'index': 192, 'url': ''},
{'available': True, 'name': 'Goldenfin', 'max': 19.9, 'index': 193, 'url': ''},
{'available': False, 'name': 'Gigantshark', 'max': 123.9, 'index': 194, 'url': ''},
{'available': False, 'name': 'Armorer', 'max': 48.9, 'index': 195, 'url': ''},
{'available': True, 'name': 'Great Gudgeon', 'max': 14.6, 'index': 196, 'url': ''},
{'available': False, 'name': 'Dark Knight', 'max': 41.2, 'index': 197, 'url': ''},
{'available': True, 'name': 'Silver Sovereign', 'max': 175.8, 'index': 198, 'url': ''},
{'available': False, 'name': 'Sabertooth Cod', 'max': 24.1, 'index': 199, 'url': ''},
{'available': False, 'name': 'Dream Goby', 'max': 12.3, 'index': 200, 'url': ''},
{'available': False, 'name': "Navigator's Brand", 'max': 35.3, 'index': 201, 'url': ''},
{'available': False, 'name': 'Dark Ambusher', 'max': 17.0, 'index': 202, 'url': ''},
{'available': False, 'name': 'Judgeray', 'max': 56.0, 'index': 203, 'url': ''},
{'available': True, 'name': 'Bloody Brewer', 'max': 15.8, 'index': 204, 'url': ''},
{'available': False, 'name': 'Faerie Queen', 'max': 26.4, 'index': 205, 'url': ''},
{'available': False, 'name': 'Slime King', 'max': 13.4, 'index': 206, 'url': ''},
{'available': True, 'name': 'Blue Widow', 'max': 26.3, 'index': 207, 'url': ''},
{'available': True, 'name': 'Ghost Carp', 'max': 34.1, 'index': 208, 'url': ''},
{'available': False, 'name': 'Carp Diem', 'max': 19.9, 'index': 209, 'url': ''},
{'available': False, 'name': 'Mud Pulgrim', 'max': 17.0, 'index': 210, 'url': ''},
{'available': False, 'name': 'Old Softie', 'max': 12.8, 'index': 211, 'url': ''},
{'available': True, 'name': 'Marrow Sucker', 'max': 22.9, 'index': 212, 'url': ''},
{'available': True, 'name': 'Chirurgeon', 'max': 26.4, 'index': 213, 'url': ''},
{'available': False, 'name': 'Mud Golem', 'max': 18.7, 'index': 214, 'url': ''},
{'available': False, 'name': 'Octomammoth', 'max': 56.5, 'index': 215, 'url': ''},
{'available': True, 'name': 'Matron Carp', 'max': 17.6, 'index': 216, 'url': ''},
{'available': True, 'name': 'High Perch', 'max': 27.6, 'index': 217, 'url': ''},
{'available': True, 'name': 'Syldra', 'max': 51.8, 'index': 218, 'url': ''},
{'available': False, 'name': 'Rivet Oyster', 'max': 14.6, 'index': 219, 'url': ''},
{'available': True, 'name': 'Jacques the Snipper', 'max': 18.7, 'index': 220, 'url': ''},
{'available': False, 'name': 'Stormdancer', 'max': 67.8, 'index': 221, 'url': ''},
{'available': False, 'name': 'Glimmerscale', 'max': 17.6, 'index': 222, 'url': ''},
{'available': True, 'name': 'Cupfish', 'max': 29.4, 'index': 223, 'url': ''},
{'available': True, 'name': 'Meteor Survivor', 'max': 25.8, 'index': 224, 'url': ''},
{'available': False, 'name': 'Joan of Trout', 'max': 31.7, 'index': 225, 'url': ''},
{'available': False, 'name': 'Toramafish', 'max': 123.8, 'index': 226, 'url': ''},
{'available': False, 'name': 'Fingers', 'max': 47.0, 'index': 227, 'url': ''},
{'available': False, 'name': 'The Assassin', 'max': 14.6, 'index': 228, 'url': ''},
{'available': True, 'name': 'Vip Viper', 'max': 38.2, 'index': 229, 'url': ''},
{'available': True, 'name': 'The Greatest Bream In The World', 'max': 79.0, 'index': 230, 'url': ''},
{'available': True, 'name': 'Dirty Herry', 'max': 64.7, 'index': 231, 'url': ''},
{'available': True, 'name': 'Old Hollow Eyes', 'max': 25.2, 'index': 232, 'url': ''},
{'available': False, 'name': 'Sylphsbane', 'max': 60.6, 'index': 233, 'url': ''},
{'available': True, 'name': 'Floating Boulder', 'max': 25.8, 'index': 234, 'url': ''},
{'available': False, 'name': 'The Grinner', 'max': 60.7, 'index': 235, 'url': ''},
{'available': True, 'name': 'Shark Tuna', 'max': 103.8, 'index': 236, 'url': ''},
{'available': False, 'name': 'Worm of Nym', 'max': 37.6, 'index': 237, 'url': ''},
{'available': False, 'name': 'Twitchbeard', 'max': 93.2, 'index': 238, 'url': ''},
{'available': False, 'name': "The Warden's Wand", 'max': 61.9, 'index': 239, 'url': ''},
{'available': True, 'name': 'Spearnose', 'max': 43.0, 'index': 240, 'url': ''},
{'available': False, 'name': 'Levinlight', 'max': 43.3, 'index': 241, 'url': ''},
{'available': False, 'name': 'The Sinker', 'max': 46.5, 'index': 242, 'url': ''},
{'available': True, 'name': 'The Gobfather', 'max': 72.4, 'index': 243, 'url': ''},
{'available': False, 'name': 'Sweetnewt', 'max': 93.1, 'index': 244, 'url': ''},
{'available': True, 'name': 'Bombardfish', 'max': 73.1, 'index': 245, 'url': ''},
{'available': True, 'name': 'The Salter', 'max': 8.7, 'index': 246, 'url': ''},
{'available': False, 'name': 'The Lone Ripper', 'max': 88.4, 'index': 247, 'url': ''},
{'available': True, 'name': 'King of the Spring', 'max': 72.9, 'index': 248, 'url': ''},
{'available': True, 'name': 'Discobolus', 'max': 64.2, 'index': 249, 'url': ''},
{'available': False, 'name': 'Iron Noose', 'max': 57.1, 'index': 250, 'url': ''},
{'available': True, 'name': 'Olgoi-Khorkhoi', 'max': 121.1, 'index': 251, 'url': ''},
{'available': True, 'name': 'Magic Carpet', 'max': 86.7, 'index': 252, 'url': ''},
{'available': False, 'name': "Daniffen's Mark", 'max': 55.2, 'index': 253, 'url': ''},
{'available': False, 'name': "Charon's Lantern", 'max': 15.1, 'index': 254, 'url': ''},
{'available': True, 'name': 'The Green Jester', 'max': 51.1, 'index': 255, 'url': ''},
{'available': True, 'name': 'Bloodbath', 'max': 56.0, 'index': 256, 'url': ''},
{'available': False, 'name': 'Son of Levin', 'max': 79.3, 'index': 257, 'url': ''},
{'available': False, 'name': 'Thundergut', 'max': 55.8, 'index': 258, 'url': ''},
{'available': True, 'name': 'The Drowned Sniper', 'max': 40.0, 'index': 259, 'url': ''},
{'available': False, 'name': 'The Terpsichorean', 'max': 32.9, 'index': 260, 'url': ''},
{'available': True, 'name': 'Mirrorscale', 'max': 24.7, 'index': 261, 'url': ''},
{'available': False, 'name': "Helmsman's Hand", 'max': 146.9, 'index': 262, 'url': ''},
{'available': False, 'name': 'The Thousand-Year Itch', 'max': 69.5, 'index': 263, 'url': ''},
{'available': True, 'name': 'Hannibal', 'max': 98.5, 'index': 264, 'url': ''},
{'available': False, 'name': 'Dawn Maiden', 'max': 57.1, 'index': 265, 'url': ''},
{'available': False, 'name': 'Starbright', 'max': 74.3, 'index': 266, 'url': ''},
{'available': True, 'name': 'The Matriarch', 'max': 8.7, 'index': 267, 'url': ''},
{'available': True, 'name': 'Shadowstreak', 'max': 69.5, 'index': 268, 'url': ''},
{'available': True, 'name': "The Captain's Chalice", 'max': 86.7, 'index': 269, 'url': ''},
{'available': False, 'name': 'Anomalocaris', 'max': 41.1, 'index': 270, 'url': ''},
{'available': False, 'name': 'Frilled Shark', 'max': 141.6, 'index': 271, 'url': ''},
{'available': False, 'name': 'Aetherlouse', 'max': 32.3, 'index': 272, 'url': ''},
{'available': False, 'name': 'Imperial Goldfish', 'max': 31.7, 'index': 273, 'url': ''},
{'available': True, 'name': 'The Old Man In The Sea', 'max': 171.1, 'index': 274, 'url': ''},
{'available': True, 'name': 'Nepto Dragon', 'max': 314.8, 'index': 275, 'url': ''},
{'available': False, 'name': 'Coelacanthus', 'max': 108.8, 'index': 276, 'url': ''},
{'available': True, 'name': 'Endoceras', 'max': 283.2, 'index': 277, 'url': ''},
{'available': False, 'name': 'Seahag', 'max': 223.1, 'index': 278, 'url': ''},
{'available': True, 'name': 'Ignus Horn', 'max': 8.7, 'index': 279, 'url': ''},
{'available': True, 'name': 'Void Bass', 'max': 91.1, 'index': 280, 'url': ''},
{'available': True, 'name': 'Cornelia', 'max': 68.4, 'index': 281, 'url': ''},
{'available': False, 'name': 'Ninja Betta', 'max': 19.3, 'index': 282, 'url': ''},
{'available': True, 'name': 'Canavan', 'max': 127.4, 'index': 283, 'url': ''},
{'available': False, 'name': 'Kuno the Killer', 'max': 208.2, 'index': 284, 'url': ''},
{'available': False, 'name': "Pirate's Bane", 'max': 265.1, 'index': 285, 'url': ''},
{'available': True, 'name': 'Ndendecki', 'max': 194.7, 'index': 286, 'url': ''},
{'available': True, 'name': "Bat-o'-Nine-Tails", 'max': 79.6, 'index': 287, 'url': ''},
{'available': False, 'name': 'Wootz Knifefish Zenith', 'max': 90.2, 'index': 288, 'url': ''},
{'available': False, 'name': 'Helicoprion', 'max': 228.7, 'index': 289, 'url': ''},
{'available': False, 'name': 'Darkstar', 'max': 81.2, 'index': 290, 'url': ''},
{'available': False, 'name': 'Blue Corpse', 'max': 64.1, 'index': 291, 'url': ''},
{'available': True, 'name': 'Mahar', 'max': 201.8, 'index': 292, 'url': ''},
{'available': True, 'name': 'Shonisaurus', 'max': 274.7, 'index': 293, 'url': ''},
{'available': True, 'name': 'Magicked Mushroom', 'max': 38.2, 'index': 294, 'url': ''},
{'available': True, 'name': 'Giant Takitaro', 'max': 141.6, 'index': 295, 'url': ''},
{'available': True, 'name': 'Namitaro', 'max': 234.1, 'index': 296, 'url': ''},
{'available': False, 'name': 'Blood Red Bonytongue', 'max': 61.9, 'index': 297, 'url': ''},
{'available': False, 'name': 'Gigant Clam', 'max': 139.4, 'index': 298, 'url': ''},
{'available': False, 'name': 'Icepick', 'max': 12.1, 'index': 299, 'url': ''},
{'available': False, 'name': 'Piece of Cloud Coral', 'max': 53.4, 'index': 300, 'url': ''},
{'available': False, 'name': 'Ice Faerie', 'max': 3.0, 'index': 301, 'url': ''},
{'available': True, 'name': 'Skyworm', 'max': 21.7, 'index': 302, 'url': ''},
{'available': True, 'name': 'Coerthan Crab', 'max': 12.4, 'index': 303, 'url': ''},
{'available': False, 'name': 'Fanged Clam', 'max': 23.1, 'index': 304, 'url': ''},
{'available': False, 'name': 'Lake Urchin', 'max': 9.1, 'index': 305, 'url': ''},
{'available': True, 'name': 'Whilom Catfish', 'max': 52.2, 'index': 306, 'url': ''},
{'available': False, 'name': 'Blueclaw Shrimp', 'max': 25.4, 'index': 307, 'url': ''},
{'available': False, 'name': 'Starflower', 'max': 11.3, 'index': 308, 'url': ''},
{'available': True, 'name': 'Glacier Core', 'max': 35.3, 'index': 309, 'url': ''},
{'available': True, 'name': 'Ogre Horn Snail', 'max': 11.7, 'index': 310, 'url': ''},
{'available': False, 'name': 'Sorcerer Fish', 'max': 73.5, 'index': 311, 'url': ''},
{'available': False, 'name': 'Hotrod', 'max': 65.6, 'index': 312, 'url': ''},
{'available': True, 'name': 'Maiboi', 'max': 43.2, 'index': 313, 'url': ''},
{'available': False, 'name': 'Three-Lip Carp', 'max': 72.7, 'index': 314, 'url': ''},
{'available': True, 'name': 'Bullfrog', 'max': 12.5, 'index': 315, 'url': ''},
{'available': True, 'name': 'Cloudfish', 'max': 6.9, 'index': 316, 'url': ''},
{'available': True, 'name': 'Mahu Wai', 'max': 19.5, 'index': 317, 'url': ''},
{'available': False, 'name': 'Rock Mussel', 'max': 6.1, 'index': 318, 'url': ''},
{'available': True, 'name': 'Buoyant Oviform', 'max': 10.9, 'index': 319, 'url': ''},
{'available': True, 'name': 'Whiteloom', 'max': 30.6, 'index': 320, 'url': ''},
{'available': True, 'name': 'Piece of Blue Cloud Coral', 'max': 38.8, 'index': 321, 'url': ''},
{'available': True, 'name': 'Seema Patrician', 'max': 38.4, 'index': 322, 'url': ''},
{'available': True, 'name': 'Ammonite', 'max': 29.8, 'index': 323, 'url': ''},
{'available': False, 'name': 'Bubble Eye', 'max': 18.4, 'index': 324, 'url': ''},
{'available': True, 'name': 'Grass Carp', 'max': 82.5, 'index': 325, 'url': ''},
{'available': False, 'name': 'Pipira Pira', 'max': 38.8, 'index': 326, 'url': ''},
{'available': True, 'name': 'Dravanian Squeaker', 'max': 18.0, 'index': 327, 'url': ''},
{'available': False, 'name': 'Kissing Fish', 'max': 25.4, 'index': 328, 'url': ''},
{'available': False, 'name': 'Mitre Slug', 'max': 47.9, 'index': 329, 'url': ''},
{'available': True, 'name': 'Lava Crab', 'max': 34.5, 'index': 330, 'url': ''},
{'available': False, 'name': 'Storm Core', 'max': 34.8, 'index': 331, 'url': ''},
{'available': False, 'name': 'Scholar Sculpin', 'max': 21.9, 'index': 332, 'url': ''},
{'available': False, 'name': 'Gigant Grouper', 'max': 109.3, 'index': 333, 'url': ''},
{'available': True, 'name': 'Vanuhead', 'max': 56.9, 'index': 334, 'url': ''},
{'available': False, 'name': 'Marble Oscar', 'max': 26.6, 'index': 335, 'url': ''},
{'available': True, 'name': 'Lungfish', 'max': 60.5, 'index': 336, 'url': ''},
{'available': True, 'name': 'Tigerfish', 'max': 131.0, 'index': 337, 'url': ''},
{'available': True, 'name': 'Sky Faerie', 'max': 9.3, 'index': 338, 'url': ''},
{'available': False, 'name': 'Granite Crab', 'max': 27.0, 'index': 339, 'url': ''},
{'available': True, 'name': "Aithon's Colt", 'max': 31.0, 'index': 340, 'url': ''},
{'available': True, 'name': 'Shipworm', 'max': 39.2, 'index': 341, 'url': ''},
{'available': True, 'name': 'Hedgemole Cricket', 'max': 4.6, 'index': 342, 'url': ''},
{'available': False, 'name': 'Mogpom', 'max': 11.7, 'index': 343, 'url': ''},
{'available': True, 'name': 'Magma Tree', 'max': 47.9, 'index': 344, 'url': ''},
{'available': False, 'name': 'Cloud Rider', 'max': 38.0, 'index': 345, 'url': ''},
{'available': False, 'name': 'Dravanian Bass', 'max': 104.2, 'index': 346, 'url': ''},
{'available': True, 'name': 'Coerthan Puffer', 'max': 5.0, 'index': 347, 'url': ''},
{'available': False, 'name': 'Snowcaller', 'max': 92.0, 'index': 348, 'url': ''},
{'available': True, 'name': 'Dragonhead', 'max': 34.1, 'index': 349, 'url': ''},
{'available': False, 'name': 'Mercy Staff', 'max': 90.4, 'index': 350, 'url': ''},
{'available': False, 'name': 'Rime Eater', 'max': 74.3, 'index': 351, 'url': ''},
{'available': True, 'name': 'Warmwater Bichir', 'max': 77.7, 'index': 352, 'url': ''},
{'available': True, 'name': 'Noontide Oscar', 'max': 29.4, 'index': 353, 'url': ''},
{'available': True, 'name': 'Shadowhisker', 'max': 135.7, 'index': 354, 'url': ''},
{'available': False, 'name': 'Gobbie Mask', 'max': 52.2, 'index': 355, 'url': ''},
{'available': True, 'name': 'Blue Medusa', 'max': 60.5, 'index': 356, 'url': ''},
{'available': False, 'name': 'Cindersmith', 'max': 38.7, 'index': 357, 'url': ''},
{'available': False, 'name': 'Bullwhip', 'max': 14.0, 'index': 358, 'url': ''},
{'available': True, 'name': 'Tiny Axolotl', 'max': 34.1, 'index': 359, 'url': ''},
{'available': False, 'name': 'High Allagan Helmet', 'max': 27.4, 'index': 360, 'url': ''},
{'available': False, 'name': 'Platinum Fish', 'max': 21.1, 'index': 361, 'url': ''},
{'available': True, 'name': 'Aether Eye', 'max': 18.4, 'index': 362, 'url': ''},
{'available': False, 'name': 'Azysfish', 'max': 10.9, 'index': 363, 'url': ''},
{'available': False, 'name': 'Crystalfin', 'max': 15.2, 'index': 364, 'url': ''},
{'available': False, 'name': 'Sweetfish', 'max': 16.8, 'index': 365, 'url': ''},
{'available': False, 'name': 'Orn Butterfly', 'max': 21.7, 'index': 366, 'url': ''},
{'available': True, 'name': 'Hundred Fin', 'max': 44.5, 'index': 367, 'url': ''},
{'available': True, 'name': 'Autumn Leaf', 'max': 9.5, 'index': 368, 'url': ''},
{'available': True, 'name': 'Manasail', 'max': 25.8, 'index': 369, 'url': ''},
{'available': False, 'name': 'Sky Sweeper', 'max': 73.5, 'index': 370, 'url': ''},
{'available': False, 'name': 'Magma Louse', 'max': 51.8, 'index': 371, 'url': ''},
{'available': False, 'name': 'Cometoise', 'max': 65.6, 'index': 372, 'url': ''},
{'available': True, 'name': 'Aetherochemical Compound #123', 'max': 26.1, 'index': 373, 'url': ''},
{'available': True, 'name': 'Brown Bolo', 'max': 70.2, 'index': 374, 'url': ''},
{'available': False, 'name': "Philosopher's Stone", 'max': 8.9, 'index': 375, 'url': ''},
{'available': True, 'name': 'Fountfish', 'max': 53.0, 'index': 376, 'url': ''},
{'available': True, 'name': 'Weston Bowfin', 'max': 42.8, 'index': 377, 'url': ''},
{'available': False, 'name': 'Letter Puffer', 'max': 78.2, 'index': 378, 'url': ''},
{'available': True, 'name': 'Star Faerie', 'max': 13.0, 'index': 379, 'url': ''},
{'available': True, 'name': 'Piece of Gloaming Coral', 'max': 64.8, 'index': 380, 'url': ''},
{'available': False, 'name': 'Albino Octopus', 'max': 9.2, 'index': 381, 'url': ''},
{'available': False, 'name': "Dragon's Soul", 'max': 26.2, 'index': 382, 'url': ''},
{'available': False, 'name': 'Tornado Shark', 'max': 105.0, 'index': 383, 'url': ''},
{'available': False, 'name': 'Warballoon', 'max': 83.7, 'index': 384, 'url': ''},
{'available': False, 'name': 'Fossiltongue', 'max': 139.3, 'index': 385, 'url': ''},
{'available': False, 'name': 'Proto-Hropken', 'max': 34.1, 'index': 386, 'url': ''},
{'available': False, 'name': 'Caiman', 'max': 121.9, 'index': 387, 'url': ''},
{'available': True, 'name': 'Euphotic Pirarucu', 'max': 251.8, 'index': 388, 'url': ''},
{'available': False, 'name': 'Illuminati Perch', 'max': 93.9, 'index': 389, 'url': ''},
{'available': False, 'name': 'Rudderfish', 'max': 74.7, 'index': 390, 'url': ''},
{'available': False, 'name': 'Bomb Puffer', 'max': 90.5, 'index': 391, 'url': ''},
{'available': True, 'name': 'Mucous Minnow', 'max': 72.7, 'index': 392, 'url': ''},
{'available': True, 'name': 'Unidentified Flying Biomass', 'max': 26.1, 'index': 393, 'url': ''},
{'available': True, 'name': 'Hospitalier Fish', 'max': 4.6, 'index': 394, 'url': ''},
{'available': True, 'name': 'Scorpionfly', 'max': 31.3, 'index': 395, 'url': ''},
{'available': False, 'name': 'Rockclimber', 'max': 9.7, 'index': 396, 'url': ''},
{'available': False, 'name': 'Blood Skipper', 'max': 18.4, 'index': 397, 'url': ''},
{'available': True, 'name': 'Cobrafish', 'max': 95.5, 'index': 398, 'url': ''},
{'available': True, 'name': 'Moogle Spirit', 'max': 127.0, 'index': 399, 'url': ''},
{'available': True, 'name': 'Oil Eel', 'max': 92.4, 'index': 400, 'url': ''},
{'available': True, 'name': 'Jeweled Jellyfish', 'max': 82.5, 'index': 401, 'url': ''},
{'available': True, 'name': 'Battle Galley', 'max': 31.3, 'index': 402, 'url': ''},
{'available': False, 'name': 'Yalm Lobster', 'max': 53.0, 'index': 403, 'url': ''},
{'available': True, 'name': 'Hinterlands Perch', 'max': 66.4, 'index': 404, 'url': ''},
{'available': False, 'name': 'Oven Catfish', 'max': 145.5, 'index': 405, 'url': ''},
{'available': False, 'name': 'Pteranodon', 'max': 177.0, 'index': 406, 'url': ''},
{'available': False, 'name': 'Winged Gurnard', 'max': 51.0, 'index': 407, 'url': ''},
{'available': True, 'name': 'Spring Urchin', 'max': 13.0, 'index': 408, 'url': ''},
{'available': True, 'name': 'Cherry Trout', 'max': 25.2, 'index': 409, 'url': ''},
{'available': False, 'name': 'Stupendemys', 'max': 162.4, 'index': 410, 'url': ''},
{'available': False, 'name': 'Black Magefish', 'max': 153.4, 'index': 411, 'url': ''},
{'available': False, 'name': 'Barreleye', 'max': 97.5, 'index': 412, 'url': ''},
{'available': True, 'name': 'Thunderbolt Eel', 'max': 86.5, 'index': 413, 'url': ''},
{'available': True, 'name': 'Catkiller', 'max': 247.9, 'index': 414, 'url': ''},
{'available': True, 'name': 'Loosetongue', 'max': 259.6, 'index': 415, 'url': ''},
{'available': False, 'name': 'Thaliak Caiman', 'max': 181.0, 'index': 416, 'url': ''},
{'available': True, 'name': 'Lavalord', 'max': 214.7, 'index': 417, 'url': ''},
{'available': True, 'name': 'Tupuxuara', 'max': 247.9, 'index': 418, 'url': ''},
{'available': True, 'name': 'Vampiric Tapestry', 'max': 139.2, 'index': 419, 'url': ''},
{'available': True, 'name': 'Storm Chaser', 'max': 153.4, 'index': 420, 'url': ''},
{'available': True, 'name': 'Berserker Betta', 'max': 10.9, 'index': 421, 'url': ''},
{'available': False, 'name': 'Capelin', 'max': 9.7, 'index': 422, 'url': ''},
{'available': True, 'name': 'Functional Proto-Hropken', 'max': 36.1, 'index': 423, 'url': ''},
{'available': True, 'name': 'Coerthan Clione', 'max': 3.0, 'index': 424, 'url': ''},
{'available': False, 'name': 'Dravanian Smelt', 'max': 9.7, 'index': 425, 'url': ''},
{'available': False, 'name': 'Piece of Heavens Coral', 'max': 64.7, 'index': 426, 'url': ''},
{'available': True, 'name': 'Sunsail', 'max': 25.6, 'index': 427, 'url': ''},
{'available': False, 'name': 'Goblin Bass', 'max': 104.2, 'index': 428, 'url': ''},
{'available': False, 'name': 'Pterodactyl', 'max': 216.4, 'index': 429, 'url': ''},
{'available': False, 'name': 'Eurhinosaur', 'max': 272.5, 'index': 430, 'url': ''},
{'available': False, 'name': 'Gem Marimo', 'max': 15.6, 'index': 431, 'url': ''},
{'available': False, 'name': 'Crown Trout', 'max': 29.1, 'index': 432, 'url': ''},
{'available': False, 'name': 'Retribution Staff', 'max': 98.3, 'index': 433, 'url': ''},
{'available': True, 'name': 'Thief Betta', 'max': 12.0, 'index': 434, 'url': ''},
{'available': True, 'name': 'Goldsmith Crab', 'max': 13.4, 'index': 435, 'url': ''},
{'available': False, 'name': 'Amber Salamander', 'max': 93.2, 'index': 436, 'url': ''},
{'available': True, 'name': 'Gnomefish', 'max': 8.9, 'index': 437, 'url': ''},
{'available': False, 'name': 'Fleece Stingray', 'max': 126.9, 'index': 438, 'url': ''},
{'available': True, 'name': 'Nyctosaur', 'max': 177.0, 'index': 439, 'url': ''},
{'available': False, 'name': 'Lava Snail', 'max': 6.9, 'index': 440, 'url': ''},
{'available': False, 'name': 'Priestfish', 'max': 58.5, 'index': 441, 'url': ''},
{'available': False, 'name': 'Coerthan Oyster', 'max': 12.4, 'index': 442, 'url': ''},
{'available': False, 'name': "Olpihant's Trunk", 'max': 42.9, 'index': 443, 'url': ''},
{'available': True, 'name': 'Mountain Kraken', 'max': 117.6, 'index': 444, 'url': ''},
{'available': True, 'name': 'Armored Catfish', 'max': 62.0, 'index': 445, 'url': ''},
{'available': True, 'name': 'Magic Bucket', 'max': 9.9, 'index': 446, 'url': ''},
{'available': False, 'name': 'Fat Purse', 'max': 8.6, 'index': 447, 'url': ''},
{'available': False, 'name': 'The Impaler', 'max': 22.2, 'index': 448, 'url': ''},
{'available': False, 'name': 'La Reale', 'max': 56.5, 'index': 449, 'url': ''},
{'available': False, 'name': 'Scaleripper', 'max': 298.5, 'index': 450, 'url': ''},
{'available': True, 'name': 'The Dreamweaver', 'max': 139.5, 'index': 451, 'url': ''},
{'available': True, 'name': 'Meteortoise', 'max': 118.0, 'index': 452, 'url': ''},
{'available': True, 'name': 'The Ewer King', 'max': 119.6, 'index': 453, 'url': ''},
{'available': False, 'name': 'Vidofnir', 'max': 52.0, 'index': 454, 'url': ''},
{'available': True, 'name': 'The Soul Of The Martyr', 'max': 529.3, 'index': 455, 'url': ''},
{'available': False, 'name': 'Inkfish', 'max': 34.1, 'index': 456, 'url': ''},
{'available': True, 'name': 'The Second One', 'max': 178.2, 'index': 457, 'url': ''},
{'available': False, 'name': 'Augmented High Allagan Helmet', 'max': 46.7, 'index': 458, 'url': ''},
{'available': False, 'name': 'Aphotic Pirarucu', 'max': 445.9, 'index': 459, 'url': ''},
{'available': False, 'name': 'Dimorphodon', 'max': 230.1, 'index': 460, 'url': ''},
{'available': True, 'name': 'Basking Shark', 'max': 538.5, 'index': 461, 'url': ''},
{'available': True, 'name': 'Allagan Bladeshark', 'max': 104.9, 'index': 462, 'url': ''},
{'available': False, 'name': 'Hailfinder', 'max': 96.6, 'index': 463, 'url': ''},
{'available': True, 'name': 'Flarefish', 'max': 95.2, 'index': 464, 'url': ''},
{'available': False, 'name': 'Twin-Tongued Carp', 'max': 108.3, 'index': 465, 'url': ''},
{'available': True, 'name': 'Madam Butterfly', 'max': 23.8, 'index': 466, 'url': ''},
{'available': True, 'name': 'Moggle Mogpom', 'max': 15.6, 'index': 467, 'url': ''},
{'available': True, 'name': 'Cirrostratus', 'max': 186.9, 'index': 468, 'url': ''},
{'available': True, 'name': "Hraesvelgr's Tear", 'max': 33.5, 'index': 469, 'url': ''},
{'available': True, 'name': 'Aetherochemical Compound #666', 'max': 24.2, 'index': 470, 'url': ''},
{'available': True, 'name': 'Hundred-Eyed Axolotl', 'max': 34.0, 'index': 471, 'url': ''},
{'available': True, 'name': 'Bobgoblin Bass', 'max': 156.0, 'index': 472, 'url': ''},
{'available': True, 'name': 'Merciless', 'max': 117.5, 'index': 473, 'url': ''},
{'available': True, 'name': 'Bishopfish', 'max': 75.6, 'index': 474, 'url': ''},
{'available': True, 'name': 'Captain Nemo', 'max': 38.7, 'index': 475, 'url': ''},
{'available': True, 'name': 'Pakiller', 'max': 321.6, 'index': 476, 'url': ''},
{'available': True, 'name': 'Ceti', 'max': 51.2, 'index': 477, 'url': ''},
{'available': True, 'name': 'Crystal Pigeon', 'max': 209.7, 'index': 478, 'url': ''},
{'available': True, 'name': 'Thunderscale', 'max': 129.9, 'index': 479, 'url': ''},
{'available': True, 'name': 'Riddle', 'max': 66.9, 'index': 480, 'url': ''},
{'available': True, 'name': 'The Lord of Lords', 'max': 302.5, 'index': 481, 'url': ''},
{'available': True, 'name': 'The Speaker', 'max': 80.9, 'index': 482, 'url': ''},
{'available': True, 'name': 'Thousand Fin', 'max': 61.5, 'index': 483, 'url': ''},
{'available': True, 'name': 'Bloodchaser', 'max': 197.5, 'index': 484, 'url': ''},
{'available': True, 'name': 'Problematicus', 'max': 1056.8, 'index': 485, 'url': ''},
{'available': True, 'name': 'Opabinia', 'max': 62.0, 'index': 486, 'url': ''},
{'available': True, 'name': 'Armor Fish', 'max': 9.6, 'index': 487, 'url': ''},
{'available': True, 'name': 'Sea Butterfly', 'max': 4.5, 'index': 488, 'url': ''},
{'available': True, 'name': 'Charibenet', 'max': 3.8, 'index': 489, 'url': ''},
{'available': True, 'name': 'Raimdellopterus', 'max': 227.2, 'index': 490, 'url': ''},
{'available': True, 'name': 'Thavnairian Leaf', 'max': 34.5, 'index': 491, 'url': ''},
{'available': False, 'name': 'Ghost Faerie', 'max': 3.0, 'index': 492, 'url': ''},
{'available': True, 'name': 'Piece of Red Sky Coral', 'max': 64.8, 'index': 493, 'url': ''},
{'available': False, 'name': "Lovers' Clam", 'max': 8.9, 'index': 494, 'url': ''},
{'available': False, 'name': 'River Shrimp', 'max': 14.8, 'index': 495, 'url': ''},
{'available': False, 'name': 'Peteinosaur', 'max': 216.3, 'index': 496, 'url': ''},
{'available': True, 'name': 'Commet Minow', 'max': 7.6, 'index': 497, 'url': ''},
{'available': True, 'name': 'Golden Chiclid', 'max': 5.3, 'index': 498, 'url': ''},
{'available': True, 'name': 'Abalathian Bitterline', 'max': 3.8, 'index': 499, 'url': ''},
{'available': True, 'name': 'Idle Goby', 'max': 37.0, 'index': 500, 'url': ''},
{'available': True, 'name': 'Steelhead Trout', 'max': 31.2, 'index': 501, 'url': ''},
{'available': True, 'name': 'Broken Crab', 'max': 9.7, 'index': 502, 'url': ''},
{'available': True, 'name': 'Miounnefish', 'max': 38.8, 'index': 503, 'url': ''},
{'available': True, 'name': 'Temple Carp', 'max': 13.0, 'index': 504, 'url': ''},
{'available': True, 'name': 'Balloon Frog', 'max': 12.4, 'index': 505, 'url': ''},
{'available': True, 'name': 'Lantern Marimo', 'max': 10.1, 'index': 506, 'url': ''},
{'available': True, 'name': 'Rapids Jumper', 'max': 39.2, 'index': 507, 'url': ''},
{'available': True, 'name': 'Adamantium Bichir', 'max': 70.7, 'index': 508, 'url': ''},
{'available': True, 'name': 'Bone Melter', 'max': 15.2, 'index': 509, 'url': ''},
{'available': True, 'name': 'Fallen Leaf', 'max': 9.5, 'index': 510, 'url': ''},
{'available': True, 'name': 'Velodyna Grass Carp', 'max': 77.8, 'index': 511, 'url': ''},
{'available': True, 'name': 'Highland Perch', 'max': 93.4, 'index': 512, 'url': ''},
{'available': True, 'name': 'Greenstream Loach', 'max': 19.3, 'index': 513, 'url': ''},
{'available': True, 'name': 'Mirage Chub', 'max': 19.3, 'index': 514, 'url': ''},
{'available': True, 'name': 'Padjali Loach', 'max': 3.8, 'index': 515, 'url': ''},
{'available': True, 'name': 'Gyr Abanian Trout', 'max': 9.7, 'index': 516, 'url': ''},
{'available': True, 'name': 'Bloodsipper', 'max': 17.6, 'index': 517, 'url': ''},
{'available': True, 'name': 'Monk Betta', 'max': 19.5, 'index': 518, 'url': ''},
{'available': True, 'name': 'Gilfish', 'max': 16.3, 'index': 519, 'url': ''},
{'available': True, 'name': 'Falling Star', 'max': 10.0, 'index': 520, 'url': ''},
{'available': True, 'name': 'Capsized Squeaker', 'max': 18.0, 'index': 521, 'url': ''},
{'available': True, 'name': 'Nirvana Crab', 'max': 25.0, 'index': 522, 'url': ''},
{'available': True, 'name': 'Gravel Gudgeon', 'max': 9.7, 'index': 523, 'url': ''},
{'available': True, 'name': 'Glass Herring', 'max': 12.8, 'index': 524, 'url': ''},
{'available': True, 'name': 'Hellyfish', 'max': 10.9, 'index': 525, 'url': ''},
{'available': True, 'name': 'Piece of Ruby Coral', 'max': 25.0, 'index': 526, 'url': ''},
{'available': True, 'name': 'Piece of Sapphire Coral', 'max': 25.0, 'index': 527, 'url': ''},
{'available': True, 'name': 'Piece of Bone Coral', 'max': 25.0, 'index': 528, 'url': ''},
{'available': True, 'name': 'Ruby Shrimp', 'max': 8.5, 'index': 529, 'url': ''},
{'available': True, 'name': 'Coeurl Snake Eel', 'max': 39.2, 'index': 530, 'url': ''},
{'available': True, 'name': 'Heather Charr', 'max': 8.5, 'index': 531, 'url': ''},
{'available': False, 'name': 'Electric Catfish', 'max': 30.0, 'index': 532, 'url': ''},
{'available': True, 'name': 'Death Loach', 'max': 8.9, 'index': 533, 'url': ''},
{'available': True, 'name': 'Grymm Crab', 'max': 12.3, 'index': 534, 'url': ''},
{'available': True, 'name': 'Invisible Crayfish', 'max': 8.5, 'index': 535, 'url': ''},
{'available': True, 'name': 'Abalathian Salamander', 'max': 6.1, 'index': 536, 'url': ''},
{'available': False, 'name': 'Cave Killifish', 'max': 8.9, 'index': 537, 'url': ''},
{'available': True, 'name': "Rhalgr's Bolt", 'max': 86.4, 'index': 538, 'url': ''},
{'available': True, 'name': 'Butterfly Fish', 'max': 13.1, 'index': 539, 'url': ''},
{'available': True, 'name': 'Dafu', 'max': 97.6, 'index': 540, 'url': ''},
{'available': True, 'name': 'Leaf Tatsunoko', 'max': 34.5, 'index': 541, 'url': ''},
{'available': True, 'name': 'Glass Flounder', 'max': 13.6, 'index': 542, 'url': ''},
{'available': True, 'name': 'Gliding Fish', 'max': 23.5, 'index': 543, 'url': ''},
{'available': True, 'name': 'Globefish', 'max': 48.7, 'index': 544, 'url': ''},
{'available': True, 'name': 'Fan Clam', 'max': 82.5, 'index': 545, 'url': ''},
{'available': True, 'name': 'Striped Fugu', 'max': 21.5, 'index': 546, 'url': ''},
{'available': True, 'name': 'Ruby Meagre', 'max': 58.7, 'index': 547, 'url': ''},
{'available': True, 'name': 'River Barramundi', 'max': 15.4, 'index': 548, 'url': ''},
{'available': True, 'name': 'Nogoi', 'max': 23.3, 'index': 549, 'url': ''},
{'available': True, 'name': 'Pagan Pirarucu', 'max': 104.7, 'index': 550, 'url': ''},
{'available': True, 'name': 'Enid Shrimp', 'max': 25.4, 'index': 551, 'url': ''},
{'available': False, 'name': 'Black Velodyna Carp', 'max': 11.5, 'index': 552, 'url': ''},
{'available': True, 'name': 'Yanxian Koi', 'max': 51.3, 'index': 553, 'url': ''},
{'available': True, 'name': 'Longhair Catfish', 'max': 62.4, 'index': 554, 'url': ''},
{'available': False, 'name': 'Doman Trout', 'max': 9.7, 'index': 555, 'url': ''},
{'available': True, 'name': 'Yanxian Barramundi', 'max': 77.6, 'index': 556, 'url': ''},
{'available': True, 'name': 'Tail Mountains Minnow', 'max': 1.4, 'index': 557, 'url': ''},
{'available': True, 'name': 'Killifish', 'max': 1.2, 'index': 558, 'url': ''},
{'available': True, 'name': 'Doman Crayfish', 'max': 6.9, 'index': 559, 'url': ''},
{'available': True, 'name': 'Othardian Trout', 'max': 21.1, 'index': 560, 'url': ''},
{'available': True, 'name': 'Zagas Khaal', 'max': 9.7, 'index': 561, 'url': ''},
{'available': True, 'name': 'Steppe Skipper', 'max': 10.9, 'index': 562, 'url': ''},
{'available': True, 'name': 'Sun Bass', 'max': 60.9, 'index': 563, 'url': ''},
{'available': True, 'name': 'Dawn Crayfish', 'max': 10.1, 'index': 564, 'url': ''},
{'available': True, 'name': 'Curtain Pleco', 'max': 45.5, 'index': 565, 'url': ''},
{'available': True, 'name': 'Yat Goby', 'max': 1.8, 'index': 566, 'url': ''},
{'available': True, 'name': "Nhaama's Boon", 'max': 27.4, 'index': 567, 'url': ''},
{'available': True, 'name': 'Doman Eel', 'max': 25.0, 'index': 568, 'url': ''},
{'available': True, 'name': 'Brassfish', 'max': 11.7, 'index': 569, 'url': ''},
{'available': True, 'name': 'Dry Steppe Skipper', 'max': 12.1, 'index': 570, 'url': ''},
{'available': True, 'name': 'Skytear', 'max': 8.9, 'index': 571, 'url': ''},
{'available': True, 'name': 'Dusk Crayfish', 'max': 10.1, 'index': 572, 'url': ''},
{'available': True, 'name': 'Bowfish', 'max': 43.6, 'index': 573, 'url': ''},
{'available': True, 'name': 'Jade Sculpin', 'max': 17.3, 'index': 574, 'url': ''},
{'available': True, 'name': 'Hardscale', 'max': 70.7, 'index': 575, 'url': ''},
{'available': True, 'name': 'Doman Grass Carp', 'max': 78.4, 'index': 576, 'url': ''},
{'available': True, 'name': 'Samurai Fish', 'max': 1.8, 'index': 577, 'url': ''},
{'available': True, 'name': 'Tao Bitterling', 'max': 5.8, 'index': 578, 'url': ''},
{'available': True, 'name': 'Blank Oscar', 'max': 29.4, 'index': 579, 'url': ''},
{'available': True, 'name': 'Dragonfish', 'max': 41.2, 'index': 580, 'url': ''},
{'available': True, 'name': 'Lordly Salmon', 'max': 17.6, 'index': 581, 'url': ''},
{'available': True, 'name': 'Yellow Prismfish', 'max': 23.5, 'index': 582, 'url': ''},
{'available': True, 'name': 'Blue Prismfish', 'max': 23.5, 'index': 583, 'url': ''},
{'available': True, 'name': "Bull's Bite", 'max': 37.3, 'index': 584, 'url': ''},
{'available': True, 'name': 'Peeping Pisces', 'max': 18.0, 'index': 585, 'url': ''},
{'available': True, 'name': 'Gigant Bass', 'max': 43.2, 'index': 586, 'url': ''},
{'available': False, 'name': 'Daio Squid', 'max': 117.6, 'index': 587, 'url': ''},
{'available': True, 'name': 'Koromo Octopus', 'max': 149.5, 'index': 588, 'url': ''},
{'available': True, 'name': 'Glass Tuna', 'max': 69.1, 'index': 589, 'url': ''},
{'available': False, 'name': 'Raitonfish', 'max': 52.0, 'index': 590, 'url': ''},
{'available': True, 'name': 'Eastern Pike', 'max': 58.9, 'index': 591, 'url': ''},
{'available': True, 'name': 'Rock Saltfish', 'max': 7.7, 'index': 592, 'url': ''},
{'available': True, 'name': 'Tawny Wench Shark', 'max': 125.7, 'index': 593, 'url': ''},
{'available': True, 'name': 'Zekki Grouper', 'max': 23.5, 'index': 594, 'url': ''},
{'available': True, 'name': 'Saltshield Snapper', 'max': 162.3, 'index': 595, 'url': ''},
{'available': True, 'name': 'Meditator', 'max': 60.4, 'index': 596, 'url': ''},
{'available': True, 'name': 'Stonytongue', 'max': 41.2, 'index': 597, 'url': ''},
{'available': True, 'name': 'Scimitarfish', 'max': 43.6, 'index': 598, 'url': ''},
{'available': True, 'name': 'Blockhead', 'max': 165.1, 'index': 599, 'url': ''},
{'available': True, 'name': 'Kotsu Zetsu', 'max': 106.0, 'index': 600, 'url': ''},
{'available': True, 'name': 'Pandamoth', 'max': 18.4, 'index': 601, 'url': ''},
{'available': True, 'name': 'Liopleurodon', 'max': 460.7, 'index': 602, 'url': ''},
{'available': True, 'name': 'Ala Mhigan Ribbon', 'max': 4.8, 'index': 603, 'url': ''},
{'available': True, 'name': 'Seraphim', 'max': 5.8, 'index': 604, 'url': ''},
{'available': True, 'name': 'Blackfin Snake Eel', 'max': 38.8, 'index': 605, 'url': ''},
{'available': True, 'name': 'Sweatfish', 'max': 5.8, 'index': 606, 'url': ''},
{'available': True, 'name': 'Hak Bitterling', 'max': 4.2, 'index': 607, 'url': ''},
{'available': True, 'name': 'Whitehorse', 'max': 13.6, 'index': 608, 'url': ''},
{'available': True, 'name': 'Sculptor', 'max': 194.9, 'index': 609, 'url': ''},
{'available': True, 'name': 'Pearl-Eye', 'max': 80.6, 'index': 610, 'url': ''},
{'available': True, 'name': 'Steelshark', 'max': 11.7, 'index': 611, 'url': ''},
{'available': True, 'name': 'Harutsuge', 'max': 12.6, 'index': 612, 'url': ''},
{'available': True, 'name': 'Silken Koi', 'max': 78.3, 'index': 613, 'url': ''},
{'available': True, 'name': 'Hanatatsu', 'max': 97.3, 'index': 614, 'url': ''},
{'available': True, 'name': 'Deemster', 'max': 93.7, 'index': 615, 'url': ''},
{'available': True, 'name': 'Swordfish', 'max': 113.8, 'index': 616, 'url': ''},
{'available': False, 'name': 'Plum Gazer', 'max': 21.5, 'index': 617, 'url': ''},
{'available': False, 'name': 'Zekki Gator', 'max': 180.9, 'index': 618, 'url': ''},
{'available': True, 'name': 'Wraithfish', 'max': 24.5, 'index': 619, 'url': ''},
{'available': True, 'name': 'Castaway Chocobo Chick', 'max': 9.9, 'index': 620, 'url': ''},
{'available': True, 'name': 'Little Perykos', 'max': 175.9, 'index': 621, 'url': ''},
{'available': True, 'name': 'Wentletrap', 'max': 1.8, 'index': 622, 'url': ''},
{'available': True, 'name': 'Black Boxfish', 'max': 15.6, 'index': 623, 'url': ''},
{'available': False, 'name': 'Glass Manta', 'max': 79.1, 'index': 624, 'url': ''},
{'available': False, 'name': 'Regal Silverside', 'max': 2.0, 'index': 625, 'url': ''},
{'available': True, 'name': 'Snowflake Moray', 'max': 16.8, 'index': 626, 'url': ''},
{'available': True, 'name': 'Hoppfish', 'max': 1.8, 'index': 627, 'url': ''},
{'available': True, 'name': 'Lightscale', 'max': 78.7, 'index': 628, 'url': ''},
{'available': True, 'name': 'Grass Fugu', 'max': 15.6, 'index': 629, 'url': ''},
{'available': True, 'name': 'Giant Eel', 'max': 78.7, 'index': 630, 'url': ''},
{'available': True, 'name': 'Kamina Crab', 'max': 1.9, 'index': 631, 'url': ''},
{'available': True, 'name': 'Spider Crab', 'max': 80.2, 'index': 632, 'url': ''},
{'available': True, 'name': 'Little Dragonfish', 'max': 22.2, 'index': 633, 'url': ''},
{'available': True, 'name': 'Black Fanfish', 'max': 80.5, 'index': 634, 'url': ''},
{'available': True, 'name': 'Zebra Shark', 'max': 80.8, 'index': 635, 'url': ''},
{'available': True, 'name': "Nophica's Comb", 'max': 3.0, 'index': 636, 'url': ''},
{'available': True, 'name': 'Warty Wartfish', 'max': 19.6, 'index': 637, 'url': ''},
{'available': True, 'name': 'Common Whelk', 'max': 2.8, 'index': 638, 'url': ''},
{'available': True, 'name': 'Hairless Barb', 'max': 79.0, 'index': 639, 'url': ''},
{'available': True, 'name': 'Hatchetfish', 'max': 3.9, 'index': 640, 'url': ''},
{'available': True, 'name': 'Threadfish', 'max': 27.5, 'index': 641, 'url': ''},
{'available': True, 'name': 'Garden Eel', 'max': 4.1, 'index': 642, 'url': ''},
{'available': True, 'name': 'Eastern Sea Pickle', 'max': 4.0, 'index': 643, 'url': ''},
{'available': True, 'name': 'Brindlebass', 'max': 89.6, 'index': 644, 'url': ''},
{'available': True, 'name': 'Demon Stonefish', 'max': 27.9, 'index': 645, 'url': ''},
{'available': True, 'name': 'Armored Crayfish', 'max': 3.8, 'index': 646, 'url': ''},
{'available': True, 'name': 'Bighead Carp', 'max': 88.0, 'index': 647, 'url': ''},
{'available': True, 'name': 'Zeni Clam', 'max': 4.1, 'index': 648, 'url': ''},
{'available': True, 'name': 'Corpse-Eater', 'max': 90.9, 'index': 649, 'url': ''},
{'available': True, 'name': 'Ronin Trevally', 'max': 90.9, 'index': 650, 'url': ''},
{'available': True, 'name': 'Toothsome Grouper', 'max': 89.6, 'index': 651, 'url': ''},
{'available': True, 'name': 'Horned Turban', 'max': 5.0, 'index': 652, 'url': ''},
{'available': True, 'name': 'Ruby Sea Star', 'max': 5.1, 'index': 653, 'url': ''},
{'available': True, 'name': 'Gauntlet Crab', 'max': 4.9, 'index': 654, 'url': ''},
{'available': True, 'name': 'Hermit Goby', 'max': 23.4, 'index': 655, 'url': ''},
{'available': True, 'name': 'Skythorn', 'max': 87.2, 'index': 656, 'url': ''},
{'available': True, 'name': 'Swordtip', 'max': 33.1, 'index': 657, 'url': ''},
{'available': True, 'name': 'False Scad', 'max': 33.2, 'index': 658, 'url': ''},
{'available': True, 'name': 'Snow Crab', 'max': 33.4, 'index': 659, 'url': ''},
{'available': True, 'name': 'Red-Eyed Lates', 'max': 97.5, 'index': 660, 'url': ''},
{'available': True, 'name': 'Common Bitterling', 'max': 24.3, 'index': 661, 'url': ''},
{'available': True, 'name': 'Fifty-Summer Cod', 'max': 88.9, 'index': 662, 'url': ''},
{'available': True, 'name': 'Nagxian Mullet', 'max': 24.3, 'index': 663, 'url': ''},
{'available': True, 'name': 'Redcoat', 'max': 38.6, 'index': 664, 'url': ''},
{'available': True, 'name': 'Yanxian Tiger Prawn', 'max': 6.0, 'index': 665, 'url': ''},
{'available': True, 'name': 'Tengu Fan', 'max': 27.9, 'index': 666, 'url': ''},
{'available': True, 'name': 'Star Turban', 'max': 6.1, 'index': 667, 'url': ''},
{'available': True, 'name': 'Blue-Fish', 'max': 96.8, 'index': 668, 'url': ''},
{'available': True, 'name': 'Steppe Bullfrog', 'max': 3.1, 'index': 669, 'url': ''},
{'available': True, 'name': 'Cavalry Catfish', 'max': 87.9, 'index': 670, 'url': ''},
{'available': False, 'name': 'Redfin', 'max': 31.4, 'index': 671, 'url': ''},
{'available': True, 'name': 'Moondisc', 'max': 3.1, 'index': 672, 'url': ''},
{'available': True, 'name': 'Bleached Bonytongue', 'max': 88.3, 'index': 673, 'url': ''},
{'available': True, 'name': 'Salt Shark', 'max': 31.3, 'index': 674, 'url': ''},
{'available': True, 'name': "King's Mantle", 'max': 89.0, 'index': 675, 'url': ''},
{'available': True, 'name': 'Sea Lamp', 'max': 6.0, 'index': 676, 'url': ''},
{'available': True, 'name': 'Amberjack', 'max': 98.4, 'index': 677, 'url': ''},
{'available': True, 'name': 'Cherry Salmon', 'max': 97.6, 'index': 678, 'url': ''},
{'available': True, 'name': 'Yu-No-Hana Crab', 'max': 28.1, 'index': 679, 'url': ''},
{'available': True, 'name': 'Dotharli Gudgeon', 'max': 32.2, 'index': 680, 'url': ''},
{'available': True, 'name': 'River Clam', 'max': 2.8, 'index': 681, 'url': ''},
{'available': True, 'name': 'Grass Shark', 'max': 90.4, 'index': 682, 'url': ''},
{'available': True, 'name': 'Typhoon Shrimp', 'max': 34.6, 'index': 683, 'url': ''},
{'available': True, 'name': 'Rock Oyster', 'max': 4.3, 'index': 684, 'url': ''},
{'available': True, 'name': 'Salt Urchin', 'max': 4.5, 'index': 685, 'url': ''},
{'available': True, 'name': 'Carpenter Crab', 'max': 35.0, 'index': 686, 'url': ''},
{'available': True, 'name': 'Spiny Lobster', 'max': 43.5, 'index': 687, 'url': ''},
{'available': True, 'name': 'Mitsuriku Shark', 'max': 98.7, 'index': 688, 'url': ''},
{'available': True, 'name': 'Doman Bubble Eye', 'max': 7.3, 'index': 689, 'url': ''},
{'available': True, 'name': 'Dragon Squeaker', 'max': 7.1, 'index': 690, 'url': ''},
{'available': True, 'name': 'Dawn Herald', 'max': 3.9, 'index': 691, 'url': ''},
{'available': True, 'name': 'Salt Cellar', 'max': 5.7, 'index': 692, 'url': ''},
{'available': True, 'name': 'White Sturgeon', 'max': 91.4, 'index': 693, 'url': ''},
{'available': True, 'name': 'Tithe Collector', 'max': 92.0, 'index': 694, 'url': ''},
{'available': True, 'name': 'Bashful Batfish', 'max': 7.1, 'index': 695, 'url': ''},
{'available': True, 'name': 'River Bream', 'max': 32.2, 'index': 696, 'url': ''},
{'available': True, 'name': 'Snipe Eel', 'max': 100.5, 'index': 697, 'url': ''},
{'available': True, 'name': 'Cherubfish', 'max': 32.3, 'index': 698, 'url': ''},
{'available': True, 'name': 'Dusk Herald', 'max': 37.5, 'index': 699, 'url': ''},
{'available': True, 'name': 'Glaring Perch', 'max': 92.6, 'index': 700, 'url': ''},
{'available': True, 'name': 'Abalathian Pipira', 'max': 40.4, 'index': 701, 'url': ''},
{'available': True, 'name': 'Steel Loach', 'max': 6.7, 'index': 702, 'url': ''},
{'available': True, 'name': 'Ivory Sole', 'max': 41.0, 'index': 703, 'url': ''},
{'available': True, 'name': 'Motley Beakfish', 'max': 91.1, 'index': 704, 'url': ''},
{'available': True, 'name': 'Thousandfang', 'max': 100.8, 'index': 705, 'url': ''},
{'available': True, 'name': 'Icthyosaur', 'max': 102.3, 'index': 706, 'url': ''},
{'available': True, 'name': 'Sailfin', 'max': 32.5, 'index': 707, 'url': ''},
{'available': True, 'name': 'Fangshi', 'max': 36.7, 'index': 708, 'url': ''},
{'available': True, 'name': 'Flamefish', 'max': 92.9, 'index': 709, 'url': ''},
{'available': True, 'name': 'Fickle Krait', 'max': 38.6, 'index': 710, 'url': ''},
{'available': True, 'name': 'Eternal Eye', 'max': 5.1, 'index': 711, 'url': ''},
{'available': True, 'name': 'Soul of the Stallion', 'max': 6.2, 'index': 712, 'url': ''},
{'available': True, 'name': 'Flood Tuna', 'max': 91.4, 'index': 713, 'url': ''},
{'available': True, 'name': 'Mercenary Crab', 'max': 41.3, 'index': 714, 'url': ''},
{'available': True, 'name': 'Ashfish', 'max': 6.9, 'index': 715, 'url': ''},
{'available': True, 'name': 'Silken Sunfish', 'max': 92.3, 'index': 716, 'url': ''},
{'available': True, 'name': 'Moasaur', 'max': 100.1, 'index': 717, 'url': ''},
{'available': True, 'name': 'Tiny Tatsunoko', 'max': 0.6, 'index': 718, 'url': ''},
{'available': False, 'name': 'Timeworn Leather Map', 'max': 11.4, 'index': 719, 'url': ''},
{'available': True, 'name': 'Timeworn Goatskin Map', 'max': 11.4, 'index': 720, 'url': ''},
{'available': False, 'name': 'Timeworn Toadskin Map', 'max': 11.4, 'index': 721, 'url': ''},
{'available': False, 'name': 'Timeworn Boarskin Map', 'max': 11.4, 'index': 722, 'url': ''},
{'available': True, 'name': 'Timeworn Peisteskin Map', 'max': 11.4, 'index': 723, 'url': ''},
{'available': False, 'name': 'Timeworn Archaeoskin Map', 'max': 11.6, 'index': 724, 'url': ''},
{'available': True, 'name': 'Timeworn Wyvernskin Map', 'max': 11.4, 'index': 725, 'url': ''},
{'available': False, 'name': 'Timeworn Dragonskin Map', 'max': 11.6, 'index': 726, 'url': ''},
{'available': True, 'name': 'Timeworn Gaganaskin Map', 'max': 11.4, 'index': 727, 'url': ''},
{'available': True, 'name': 'Timeworn Gazelleskin Map', 'max': 11.4, 'index': 728, 'url': ''},
{'available': False, 'name': 'Steel Sky Pirate Spoil', 'max': 11.4, 'index': 729, 'url': ''}
]