fishes = [
	{'name': 'Abalathian Smelt', 'url': 'http://ff14angler.com/fish/24', 'max': 5.8},
	{'name': 'Acorn Snail', 'url': 'http://ff14angler.com/fish/34', 'max': 6.9},
	{'name': 'Aegis Shrimp', 'url': 'http://ff14angler.com/fish/59', 'max': 3.8},
	{'name': 'Aether Eye', 'url': 'http://ff14angler.com/fish/377', 'max': 18.4},
	{'name': 'Aetherlouse', 'url': 'http://ff14angler.com/fish/287', 'max': 32.3},
	{'name': 'Aetherochemical Compound #123', 'url': 'http://ff14angler.com/fish/388', 'max': 26.1},
	{'name': 'Aetherochemical Compound #666', 'url': 'http://ff14angler.com/fish/485', 'max': 24.2},
	{'name': 'Agelyss Carp', 'url': 'http://ff14angler.com/fish/128', 'max': 51.4},
	{'name': 'Aithon\'s Colt', 'url': 'http://ff14angler.com/fish/355', 'max': 31.0},
	{'name': 'Ala Mhigan Fighting Fish', 'url': 'http://ff14angler.com/fish/31', 'max': 10.9},
	{'name': 'Albino Octopus', 'url': 'http://ff14angler.com/fish/396', 'max': 9.2},
	{'name': 'Allagan Bladeshark', 'url': 'http://ff14angler.com/fish/477', 'max': 104.9},
	{'name': 'Alligator Garfish', 'url': 'http://ff14angler.com/fish/161', 'max': 65.6},
	{'name': 'Amber Salamander', 'url': 'http://ff14angler.com/fish/451', 'max': 93.2},
	{'name': 'Ammonite', 'url': 'http://ff14angler.com/fish/338', 'max': 29.8},
	{'name': 'Angelfish', 'url': 'http://ff14angler.com/fish/40', 'max': 30.2},
	{'name': 'Angry Pike', 'url': 'http://ff14angler.com/fish/145', 'max': 54.2},
	{'name': 'Anomalocaris', 'url': 'http://ff14angler.com/fish/285', 'max': 41.1},
	{'name': 'Antlion Slug', 'url': 'http://ff14angler.com/fish/106', 'max': 23.5},
	{'name': 'Aphotic Pirarucu', 'url': 'http://ff14angler.com/fish/474', 'max': 445.9},
	{'name': 'Archerfish', 'url': 'http://ff14angler.com/fish/125', 'max': 26.6},
	{'name': 'Armored Catfish', 'url': 'http://ff14angler.com/fish/460', 'max': 62.0},
	{'name': 'Armored Pleco', 'url': 'http://ff14angler.com/fish/94', 'max': 36.9},
	{'name': 'Armorer', 'url': 'http://ff14angler.com/fish/210', 'max': 48.9},
	{'name': 'Ash Tuna', 'url': 'http://ff14angler.com/fish/77', 'max': 69.1},
	{'name': 'Assassin Betta', 'url': 'http://ff14angler.com/fish/130', 'max': 12.8},
	{'name': 'Augmented High Allagan Helmet', 'url': 'http://ff14angler.com/fish/473', 'max': 46.7},
	{'name': 'Autumn Leaf', 'url': 'http://ff14angler.com/fish/383', 'max': 9.5},
	{'name': 'Azysfish', 'url': 'http://ff14angler.com/fish/378', 'max': 10.9},
	{'name': 'Balloonfish', 'url': 'http://ff14angler.com/fish/97', 'max': 48.7},
	{'name': 'Barreleye', 'url': 'http://ff14angler.com/fish/427', 'max': 97.5},
	{'name': 'Basking Shark', 'url': 'http://ff14angler.com/fish/476', 'max': 538.5},
	{'name': 'Bat-o\'-Nine-Tails', 'url': 'http://ff14angler.com/fish/302', 'max': 79.6},
	{'name': 'Battle Galley', 'url': 'http://ff14angler.com/fish/417', 'max': 31.3},
	{'name': 'Beguiler Chub', 'url': 'http://ff14angler.com/fish/202', 'max': 13.4},
	{'name': 'Berserker Betta', 'url': 'http://ff14angler.com/fish/436', 'max': 10.9},
	{'name': 'Bianaq Bream', 'url': 'http://ff14angler.com/fish/65', 'max': 52.6},
	{'name': 'Black Eel', 'url': 'http://ff14angler.com/fish/55', 'max': 25.4},
	{'name': 'Black Ghost', 'url': 'http://ff14angler.com/fish/66', 'max': 29.4},
	{'name': 'Black Magefish', 'url': 'http://ff14angler.com/fish/426', 'max': 153.4},
	{'name': 'Black Sole', 'url': 'http://ff14angler.com/fish/67', 'max': 32.5},
	{'name': 'Blacklip Oyster', 'url': 'http://ff14angler.com/fish/120', 'max': 21.5},
	{'name': 'Blind Manta', 'url': 'http://ff14angler.com/fish/137', 'max': 58.9},
	{'name': 'Blindfish', 'url': 'http://ff14angler.com/fish/25', 'max': 8.1},
	{'name': 'Blood Red Bonytongue', 'url': 'http://ff14angler.com/fish/312', 'max': 61.9},
	{'name': 'Blood Skipper', 'url': 'http://ff14angler.com/fish/412', 'max': 18.4},
	{'name': 'Bloodbath', 'url': 'http://ff14angler.com/fish/271', 'max': 56.0},
	{'name': 'Bloody Brewer', 'url': 'http://ff14angler.com/fish/219', 'max': 15.8},
	{'name': 'Blowfish', 'url': 'http://ff14angler.com/fish/49', 'max': 21.5},
	{'name': 'Blue Corpse', 'url': 'http://ff14angler.com/fish/306', 'max': 64.1},
	{'name': 'Blue Medusa', 'url': 'http://ff14angler.com/fish/371', 'max': 60.5},
	{'name': 'Blue Octopus', 'url': 'http://ff14angler.com/fish/45', 'max': 37.6},
	{'name': 'Blue Widow', 'url': 'http://ff14angler.com/fish/222', 'max': 26.3},
	{'name': 'Bluebell Salmon', 'url': 'http://ff14angler.com/fish/42', 'max': 17.6},
	{'name': 'Blueclaw Shrimp', 'url': 'http://ff14angler.com/fish/322', 'max': 25.4},
	{'name': 'Bobgoblin Bass', 'url': 'http://ff14angler.com/fish/487', 'max': 156.0},
	{'name': 'Boltfish', 'url': 'http://ff14angler.com/fish/135', 'max': 53.0},
	{'name': 'Bomb Puffer', 'url': 'http://ff14angler.com/fish/406', 'max': 90.5},
	{'name': 'Bombardfish', 'url': 'http://ff14angler.com/fish/260', 'max': 73.1},
	{'name': 'Bone Cleaner', 'url': 'http://ff14angler.com/fish/79', 'max': 15.2},
	{'name': 'Bone Crayfish', 'url': 'http://ff14angler.com/fish/9', 'max': 8.5},
	{'name': 'Bonytongue', 'url': 'http://ff14angler.com/fish/82', 'max': 41.2},
	{'name': 'Bowfin', 'url': 'http://ff14angler.com/fish/177', 'max': 56.9},
	{'name': 'Boxing Pleco', 'url': 'http://ff14angler.com/fish/141', 'max': 45.5},
	{'name': 'Brass Loach', 'url': 'http://ff14angler.com/fish/21', 'max': 8.9},
	{'name': 'Bronze Lake Trout', 'url': 'http://ff14angler.com/fish/108', 'max': 48.7},
	{'name': 'Brown Bolo', 'url': 'http://ff14angler.com/fish/389', 'max': 70.2},
	{'name': 'Bubble Eye', 'url': 'http://ff14angler.com/fish/339', 'max': 18.4},
	{'name': 'Bullfrog', 'url': 'http://ff14angler.com/fish/330', 'max': 12.5},
	{'name': 'Bullwhip', 'url': 'http://ff14angler.com/fish/373', 'max': 14.0},
	{'name': 'Buoyant Oviform', 'url': 'http://ff14angler.com/fish/334', 'max': 10.9},
	{'name': 'Cadaver Carp', 'url': 'http://ff14angler.com/fish/167', 'max': 77.4},
	{'name': 'Caiman', 'url': 'http://ff14angler.com/fish/402', 'max': 121.9},
	{'name': 'Canavan', 'url': 'http://ff14angler.com/fish/298', 'max': 127.4},
	{'name': 'Capelin', 'url': 'http://ff14angler.com/fish/437', 'max': 9.7},
	{'name': 'Caravan Eel', 'url': 'http://ff14angler.com/fish/164', 'max': 86.5},
	{'name': 'Carp Diem', 'url': 'http://ff14angler.com/fish/224', 'max': 19.9},
	{'name': 'Caterwauler', 'url': 'http://ff14angler.com/fish/204', 'max': 14.0},
	{'name': 'Catkiller', 'url': 'http://ff14angler.com/fish/429', 'max': 247.9},
	{'name': 'Cave Cherax', 'url': 'http://ff14angler.com/fish/153', 'max': 32.9},
	{'name': 'Charon\'s Lantern', 'url': 'http://ff14angler.com/fish/269', 'max': 15.1},
	{'name': 'Cherry Trout', 'url': 'http://ff14angler.com/fish/424', 'max': 25.2},
	{'name': 'Chirurgeon', 'url': 'http://ff14angler.com/fish/228', 'max': 26.4},
	{'name': 'Chub', 'url': 'http://ff14angler.com/fish/3', 'max': 8.9},
	{'name': 'Cindersmith', 'url': 'http://ff14angler.com/fish/372', 'max': 38.7},
	{'name': 'Cirrostratus', 'url': 'http://ff14angler.com/fish/483', 'max': 186.9},
	{'name': 'Climbing Perch', 'url': 'http://ff14angler.com/fish/63', 'max': 17.2},
	{'name': 'Cloud Cutter', 'url': 'http://ff14angler.com/fish/134', 'max': 28.6},
	{'name': 'Cloud Jellyfish', 'url': 'http://ff14angler.com/fish/126', 'max': 17.6},
	{'name': 'Cloud Rider', 'url': 'http://ff14angler.com/fish/360', 'max': 38.0},
	{'name': 'Cloudfish', 'url': 'http://ff14angler.com/fish/331', 'max': 6.9},
	{'name': 'Clown Loach', 'url': 'http://ff14angler.com/fish/91', 'max': 34.1},
	{'name': 'Cobrafish', 'url': 'http://ff14angler.com/fish/413', 'max': 95.5},
	{'name': 'Coerthan Clione', 'url': 'http://ff14angler.com/fish/439', 'max': 3.0},
	{'name': 'Coerthan Crab', 'url': 'http://ff14angler.com/fish/318', 'max': 12.4},
	{'name': 'Coerthan Oyster', 'url': 'http://ff14angler.com/fish/457', 'max': 12.4},
	{'name': 'Coerthan Puffer', 'url': 'http://ff14angler.com/fish/362', 'max': 5.0},
	{'name': 'Coeurlfish', 'url': 'http://ff14angler.com/fish/154', 'max': 82.5},
	{'name': 'Coelacanth', 'url': 'http://ff14angler.com/fish/166', 'max': 80.6},
	{'name': 'Coelacanthus', 'url': 'http://ff14angler.com/fish/291', 'max': 108.8},
	{'name': 'Cometoise', 'url': 'http://ff14angler.com/fish/387', 'max': 65.6},
	{'name': 'Common Sculpin', 'url': 'http://ff14angler.com/fish/119', 'max': 17.6},
	{'name': 'Copperfish', 'url': 'http://ff14angler.com/fish/41', 'max': 11.7},
	{'name': 'Coral Butterfly', 'url': 'http://ff14angler.com/fish/20', 'max': 13.2},
	{'name': 'Cornelia', 'url': 'http://ff14angler.com/fish/296', 'max': 68.4},
	{'name': 'Crayfish', 'url': 'http://ff14angler.com/fish/2', 'max': 6.9},
	{'name': 'Crimson Crayfish', 'url': 'http://ff14angler.com/fish/17', 'max': 10.1},
	{'name': 'Crimson Trout', 'url': 'http://ff14angler.com/fish/104', 'max': 38.0},
	{'name': 'Crown Trout', 'url': 'http://ff14angler.com/fish/447', 'max': 29.1},
	{'name': 'Crystal Perch', 'url': 'http://ff14angler.com/fish/205', 'max': 37.1},
	{'name': 'Crystalfin', 'url': 'http://ff14angler.com/fish/379', 'max': 15.2},
	{'name': 'Cupfish', 'url': 'http://ff14angler.com/fish/238', 'max': 29.4},
	{'name': 'Daniffen\'s Mark', 'url': 'http://ff14angler.com/fish/268', 'max': 55.2},
	{'name': 'Dark Ambusher', 'url': 'http://ff14angler.com/fish/217', 'max': 17.0},
	{'name': 'Dark Bass', 'url': 'http://ff14angler.com/fish/56', 'max': 27.4},
	{'name': 'Dark Knight', 'url': 'http://ff14angler.com/fish/212', 'max': 41.2},
	{'name': 'Dark Sleeper', 'url': 'http://ff14angler.com/fish/36', 'max': 11.3},
	{'name': 'Darkstar', 'url': 'http://ff14angler.com/fish/305', 'max': 81.2},
	{'name': 'Dawn Maiden', 'url': 'http://ff14angler.com/fish/280', 'max': 57.1},
	{'name': 'Desert Catfish', 'url': 'http://ff14angler.com/fish/96', 'max': 31.3},
	{'name': 'Dimorphodon', 'url': 'http://ff14angler.com/fish/475', 'max': 230.1},
	{'name': 'Dinichthys', 'url': 'http://ff14angler.com/fish/172', 'max': 165.2},
	{'name': 'Dirty Herry', 'url': 'http://ff14angler.com/fish/246', 'max': 64.7},
	{'name': 'Discobolus', 'url': 'http://ff14angler.com/fish/264', 'max': 64.2},
	{'name': 'Discus', 'url': 'http://ff14angler.com/fish/105', 'max': 34.5},
	{'name': 'Dragon\'s Soul', 'url': 'http://ff14angler.com/fish/397', 'max': 26.2},
	{'name': 'Dragonhead', 'url': 'http://ff14angler.com/fish/364', 'max': 34.1},
	{'name': 'Dravanian Bass', 'url': 'http://ff14angler.com/fish/361', 'max': 104.2},
	{'name': 'Dravanian Smelt', 'url': 'http://ff14angler.com/fish/440', 'max': 9.7},
	{'name': 'Dravanian Squeaker', 'url': 'http://ff14angler.com/fish/342', 'max': 18.0},
	{'name': 'Dream Goby', 'url': 'http://ff14angler.com/fish/215', 'max': 12.3},
	{'name': 'Dune Manta', 'url': 'http://ff14angler.com/fish/110', 'max': 55.0},
	{'name': 'Dusk Goby', 'url': 'http://ff14angler.com/fish/13', 'max': 8.1},
	{'name': 'Dustfish', 'url': 'http://ff14angler.com/fish/100', 'max': 28.2},
	{'name': 'Dwarf Catfish', 'url': 'http://ff14angler.com/fish/7', 'max': 9.3},
	{'name': 'Emperor Fish', 'url': 'http://ff14angler.com/fish/176', 'max': 60.9},
	{'name': 'Endoceras', 'url': 'http://ff14angler.com/fish/292', 'max': 283.2},
	{'name': 'Euphotic Pirarucu', 'url': 'http://ff14angler.com/fish/403', 'max': 251.8},
	{'name': 'Eunuch Crayfish', 'url': 'http://ff14angler.com/fish/47', 'max': 17.6},
	{'name': 'Eurhinosaur', 'url': 'http://ff14angler.com/fish/445', 'max': 272.5},
	{'name': 'Faerie Bass', 'url': 'http://ff14angler.com/fish/33', 'max': 17.6},
	{'name': 'Faerie Queen', 'url': 'http://ff14angler.com/fish/220', 'max': 26.4},
	{'name': 'Fall Jumper', 'url': 'http://ff14angler.com/fish/114', 'max': 40.4},
	{'name': 'Fanged Clam', 'url': 'http://ff14angler.com/fish/319', 'max': 23.1},
	{'name': 'Fat Purse', 'url': 'http://ff14angler.com/fish/462', 'max': 8.6},
	{'name': 'Finger Shrimp', 'url': 'http://ff14angler.com/fish/8', 'max': 8.5},
	{'name': 'Fingers', 'url': 'http://ff14angler.com/fish/242', 'max': 47.0},
	{'name': 'Five-Ilm Pleco', 'url': 'http://ff14angler.com/fish/60', 'max': 7.7},
	{'name': 'Flarefish', 'url': 'http://ff14angler.com/fish/479', 'max': 95.2},
	{'name': 'Fleece Stingray', 'url': 'http://ff14angler.com/fish/453', 'max': 126.9},
	{'name': 'Floating Boulder', 'url': 'http://ff14angler.com/fish/249', 'max': 25.8},
	{'name': 'Fossiltongue', 'url': 'http://ff14angler.com/fish/400', 'max': 139.3},
	{'name': 'Fountfish', 'url': 'http://ff14angler.com/fish/391', 'max': 53.0},
	{'name': 'Four-Eyed Fish', 'url': 'http://ff14angler.com/fish/53', 'max': 18.0},
	{'name': 'Frilled Shark', 'url': 'http://ff14angler.com/fish/286', 'max': 141.6},
	{'name': 'Fullmoon Sardine', 'url': 'http://ff14angler.com/fish/83', 'max': 21.5},
	{'name': 'Functional Proto-Hropken', 'url': 'http://ff14angler.com/fish/438', 'max': 36.1},
	{'name': 'Garpike', 'url': 'http://ff14angler.com/fish/136', 'max': 58.9},
	{'name': 'Gem Marimo', 'url': 'http://ff14angler.com/fish/446', 'max': 15.6},
	{'name': 'Ghost Carp', 'url': 'http://ff14angler.com/fish/223', 'max': 34.1},
	{'name': 'Giant Bass', 'url': 'http://ff14angler.com/fish/95', 'max': 43.2},
	{'name': 'Giant Catfish', 'url': 'http://ff14angler.com/fish/163', 'max': 70.3},
	{'name': 'Giant Donko', 'url': 'http://ff14angler.com/fish/157', 'max': 57.7},
	{'name': 'Giant Squid', 'url': 'http://ff14angler.com/fish/169', 'max': 117.6},
	{'name': 'Giant Takitaro', 'url': 'http://ff14angler.com/fish/310', 'max': 141.6},
	{'name': 'Gigant Clam', 'url': 'http://ff14angler.com/fish/313', 'max': 139.4},
	{'name': 'Gigant Grouper', 'url': 'http://ff14angler.com/fish/348', 'max': 109.3},
	{'name': 'Gigant Octopus', 'url': 'http://ff14angler.com/fish/170', 'max': 149.5},
	{'name': 'Gigantpole', 'url': 'http://ff14angler.com/fish/186', 'max': 25.6},
	{'name': 'Gigantshark', 'url': 'http://ff14angler.com/fish/209', 'max': 123.9},
	{'name': 'Glacier Core', 'url': 'http://ff14angler.com/fish/324', 'max': 35.3},
	{'name': 'Glass Perch', 'url': 'http://ff14angler.com/fish/52', 'max': 24.7},
	{'name': 'Glimmerscale', 'url': 'http://ff14angler.com/fish/237', 'max': 17.6},
	{'name': 'Gnomefish', 'url': 'http://ff14angler.com/fish/452', 'max': 8.9},
	{'name': 'Gobbie Mask', 'url': 'http://ff14angler.com/fish/370', 'max': 52.2},
	{'name': 'Goblin Bass', 'url': 'http://ff14angler.com/fish/443', 'max': 104.2},
	{'name': 'Goblin Perch', 'url': 'http://ff14angler.com/fish/127', 'max': 48.3},
	{'name': 'Golden Loach', 'url': 'http://ff14angler.com/fish/101', 'max': 41.6},
	{'name': 'Goldenfin', 'url': 'http://ff14angler.com/fish/208', 'max': 19.9},
	{'name': 'Goldfish', 'url': 'http://ff14angler.com/fish/146', 'max': 21.1},
	{'name': 'Goldsmith Crab', 'url': 'http://ff14angler.com/fish/450', 'max': 13.4},
	{'name': 'Goosefish', 'url': 'http://ff14angler.com/fish/152', 'max': 97.5},
	{'name': 'Granite Crab', 'url': 'http://ff14angler.com/fish/354', 'max': 27.0},
	{'name': 'Grass Carp', 'url': 'http://ff14angler.com/fish/340', 'max': 82.5},
	{'name': 'Great Gudgeon', 'url': 'http://en.ff14angler.com/fish/211', 'max': 14.6},
	{'name': 'Grip Killifish', 'url': 'http://en.ff14angler.com/fish/78', 'max': 8.9},
	{'name': 'Gudgeon', 'url': 'http://en.ff14angler.com/fish/19', 'max': 9.7},
	{'name': 'Hailfinder', 'url': 'http://en.ff14angler.com/fish/478', 'max': 96.6},
	{'name': 'Halibut', 'url': 'http://en.ff14angler.com/fish/160', 'max': 100.2},
	{'name': 'Hammerhead Shark', 'url': 'http://en.ff14angler.com/fish/70', 'max': 58.9},
	{'name': 'Hannibal', 'url': 'http://en.ff14angler.com/fish/279', 'max': 98.5},
	{'name': 'Haraldr Haddock', 'url': 'http://en.ff14angler.com/fish/85', 'max': 53.0},
	{'name': 'Harbor Herring', 'url': 'http://en.ff14angler.com/fish/15', 'max': 12.8},
	{'name': 'Hedgemole Cricket', 'url': 'http://en.ff14angler.com/fish/357', 'max': 4.6},
	{'name': 'Helicoprion', 'url': 'http://en.ff14angler.com/fish/304', 'max': 228.7},
	{'name': 'Heliobatis', 'url': 'http://en.ff14angler.com/fish/178', 'max': 87.1},
	{'name': 'Helmet Crab', 'url': 'http://en.ff14angler.com/fish/32', 'max': 17.2},
	{'name': 'Helmsman\'s Hand', 'url': 'http://en.ff14angler.com/fish/277', 'max': 146.9},
	{'name': 'High Allagan Helmet', 'url': 'http://en.ff14angler.com/fish/375', 'max': 27.4},
	{'name': 'High Perch', 'url': 'http://en.ff14angler.com/fish/232', 'max': 27.6},
	{'name': 'Hinterlands Perch', 'url': 'http://en.ff14angler.com/fish/419', 'max': 66.4},
	{'name': 'Hospitalier Fish', 'url': 'http://en.ff14angler.com/fish/409', 'max': 4.6},
	{'name': 'Hotrod', 'url': 'http://en.ff14angler.com/fish/327', 'max': 65.6},
	{'name': 'Hraesvelgr\'s Tear', 'url': 'http://en.ff14angler.com/fish/484', 'max': 33.5},
	{'name': 'Hundred Fin', 'url': 'http://en.ff14angler.com/fish/382', 'max': 44.5},
	{'name': 'Hundred-Eyed Axolotl', 'url': 'http://en.ff14angler.com/fish/486', 'max': 34.0},
	{'name': 'Ice Faerie', 'url': 'http://en.ff14angler.com/fish/316', 'max': 3.0},
	{'name': 'Icepick', 'url': 'http://en.ff14angler.com/fish/314', 'max': 12.1},
	{'name': 'Ignus Horn', 'url': 'http://en.ff14angler.com/fish/294', 'max': 8.7},
	{'name': 'Ignus Snail', 'url': 'http://en.ff14angler.com/fish/109', 'max': 5.8},
	{'name': 'Illuminati Perch', 'url': 'http://en.ff14angler.com/fish/404', 'max': 93.9},
	{'name': 'Ilsabardian Bass', 'url': 'http://en.ff14angler.com/fish/139', 'max': 60.9},
	{'name': 'Imperial Goldfish', 'url': 'http://en.ff14angler.com/fish/288', 'max': 31.7},
	{'name': 'Indigo Herring', 'url': 'http://en.ff14angler.com/fish/75', 'max': 43.2},
	{'name': 'Inkfish', 'url': 'http://en.ff14angler.com/fish/471', 'max': 34.1},
	{'name': 'Iron Noose', 'url': 'http://en.ff14angler.com/fish/265', 'max': 57.1},
	{'name': 'Jacques the Snipper', 'url': 'http://en.ff14angler.com/fish/235', 'max': 18.7},
	{'name': 'Jade Eel', 'url': 'http://en.ff14angler.com/fish/48', 'max': 25.0},
	{'name': 'Jeweled Jellyfish', 'url': 'http://en.ff14angler.com/fish/416', 'max': 82.5},
	{'name': 'Joan of Trout', 'url': 'http://en.ff14angler.com/fish/240', 'max': 31.7},
	{'name': 'Judgeray', 'url': 'http://en.ff14angler.com/fish/218', 'max': 56.0},
	{'name': 'Judgment Staff', 'url': 'http://en.ff14angler.com/fish/174', 'max': 53.0},
	{'name': 'Jungle Catfish', 'url': 'http://en.ff14angler.com/fish/184', 'max': 62.4},
	{'name': 'Junkmonger', 'url': 'http://en.ff14angler.com/fish/207', 'max': 146.3},
	{'name': 'King of the Spring', 'url': 'http://en.ff14angler.com/fish/263', 'max': 72.9},
	{'name': 'Kissing Fish', 'url': 'http://en.ff14angler.com/fish/343', 'max': 25.4},
	{'name': 'Kissing Trout', 'url': 'http://en.ff14angler.com/fish/144', 'max': 49.5},
	{'name': 'Knifefish', 'url': 'http://en.ff14angler.com/fish/115', 'max': 43.6},
	{'name': 'Kobold Puffer', 'url': 'http://en.ff14angler.com/fish/123', 'max': 6.9},
	{'name': 'Kuno the Killer', 'url': 'http://en.ff14angler.com/fish/299', 'max': 208.2},
	{'name': 'La Noscean Perch', 'url': 'http://en.ff14angler.com/fish/37', 'max': 18.4},
	{'name': 'La Reale', 'url': 'http://en.ff14angler.com/fish/464', 'max': 56.5},
	{'name': 'Lake Urchin', 'url': 'http://en.ff14angler.com/fish/320', 'max': 9.1},
	{'name': 'Lamp Marimo', 'url': 'http://en.ff14angler.com/fish/74', 'max': 10.1},
	{'name': 'Lamprey', 'url': 'http://en.ff14angler.com/fish/68', 'max': 28.6},
	{'name': 'Lava Crab', 'url': 'http://en.ff14angler.com/fish/345', 'max': 34.5},
	{'name': 'Lava Snail', 'url': 'http://en.ff14angler.com/fish/455', 'max': 6.9},
	{'name': 'Lavalord', 'url': 'http://en.ff14angler.com/fish/432', 'max': 214.7},
	{'name': 'Lavender Remora', 'url': 'http://en.ff14angler.com/fish/93', 'max': 60.9},
	{'name': 'Leafy Seadragon', 'url': 'http://en.ff14angler.com/fish/81', 'max': 34.5},
	{'name': 'Letter Puffer', 'url': 'http://en.ff14angler.com/fish/393', 'max': 78.2},
	{'name': 'Levinlight', 'url': 'http://en.ff14angler.com/fish/256', 'max': 43.3},
	{'name': 'Little Thalaos', 'url': 'http://en.ff14angler.com/fish/155', 'max': 118.0},
	{'name': 'Lominsan Anchovy', 'url': 'http://en.ff14angler.com/fish/5', 'max': 8.1},
	{'name': 'Loosetongue', 'url': 'http://en.ff14angler.com/fish/430', 'max': 259.6},
	{'name': 'Loyal Pleco', 'url': 'http://en.ff14angler.com/fish/112', 'max': 46.3},
	{'name': 'Lungfish', 'url': 'http://en.ff14angler.com/fish/351', 'max': 60.5},
	{'name': 'Madam Butterfly', 'url': 'http://en.ff14angler.com/fish/481', 'max': 23.8},
	{'name': 'Magic Bucket', 'url': 'http://en.ff14angler.com/fish/461', 'max': 9.9},
	{'name': 'Magic Carpet', 'url': 'http://en.ff14angler.com/fish/267', 'max': 86.7},
	{'name': 'Magicked Mushroom', 'url': 'http://en.ff14angler.com/fish/309', 'max': 38.2},
	{'name': 'Magma Louse', 'url': 'http://en.ff14angler.com/fish/386', 'max': 51.8},
	{'name': 'Magma Tree', 'url': 'http://en.ff14angler.com/fish/359', 'max': 47.9},
	{'name': 'Mahar', 'url': 'http://en.ff14angler.com/fish/307', 'max': 201.8},
	{'name': 'Mahi-Mahi', 'url': 'http://en.ff14angler.com/fish/159', 'max': 97.5},
	{'name': 'Mahu Wai', 'url': 'http://en.ff14angler.com/fish/332', 'max': 19.5},
	{'name': 'Maiboi', 'url': 'http://en.ff14angler.com/fish/328', 'max': 43.2},
	{'name': 'Maiden Carp', 'url': 'http://en.ff14angler.com/fish/23', 'max': 11.7},
	{'name': 'Manasail', 'url': 'http://en.ff14angler.com/fish/384', 'max': 25.8},
	{'name': 'Marble Oscar', 'url': 'http://en.ff14angler.com/fish/350', 'max': 26.6},
	{'name': 'Marrow Sucker', 'url': 'http://en.ff14angler.com/fish/227', 'max': 22.9},
	{'name': 'Matron Carp', 'url': 'http://en.ff14angler.com/fish/231', 'max': 17.6},
	{'name': 'Mazlaya Marlin', 'url': 'http://en.ff14angler.com/fish/165', 'max': 114.0},
	{'name': 'Megalodon', 'url': 'http://en.ff14angler.com/fish/179', 'max': 181.0},
	{'name': 'Merciless', 'url': 'http://en.ff14angler.com/fish/488', 'max': 117.5},
	{'name': 'Mercy Staff', 'url': 'http://en.ff14angler.com/fish/365', 'max': 90.4},
	{'name': 'Merlthor Goby', 'url': 'http://en.ff14angler.com/fish/4', 'max': 9.3},
	{'name': 'Meteor Survivor', 'url': 'http://en.ff14angler.com/fish/239', 'max': 25.8},
	{'name': 'Meteortoise', 'url': 'http://en.ff14angler.com/fish/467', 'max': 118.0},
	{'name': 'Mirrorscale', 'url': 'http://en.ff14angler.com/fish/276', 'max': 24.7},
	{'name': 'Mitre Slug', 'url': 'http://en.ff14angler.com/fish/344', 'max': 47.9},
	{'name': 'Mitten Crab', 'url': 'http://en.ff14angler.com/fish/84', 'max': 21.9},
	{'name': 'Moat Carp', 'url': 'http://en.ff14angler.com/fish/39', 'max': 13.2},
	{'name': 'Moggle Mogpom', 'url': 'http://en.ff14angler.com/fish/482', 'max': 15.6},
	{'name': 'Mogpom', 'url': 'http://en.ff14angler.com/fish/358', 'max': 11.7},
	{'name': 'Moldva', 'url': 'http://en.ff14angler.com/fish/206', 'max': 16.4},
	{'name': 'Monke Onke', 'url': 'http://en.ff14angler.com/fish/86', 'max': 37.3},
	{'name': 'Monkfish', 'url': 'http://en.ff14angler.com/fish/61', 'max': 58.5},
	{'name': 'Moogle Spirit', 'url': 'http://en.ff14angler.com/fish/414', 'max': 127.0},
	{'name': 'Moraby Flounder', 'url': 'http://en.ff14angler.com/fish/22', 'max': 16.3},
	{'name': 'Morinabaligi', 'url': 'http://en.ff14angler.com/fish/183', 'max': 94.3},
	{'name': 'Mountain Kraken', 'url': 'http://en.ff14angler.com/fish/459', 'max': 117.6},
	{'name': 'Mucous Minnow', 'url': 'http://en.ff14angler.com/fish/407', 'max': 72.7},
	{'name': 'Mud Golem', 'url': 'http://en.ff14angler.com/fish/229', 'max': 18.7},
	{'name': 'Mud Pulgrim', 'url': 'http://en.ff14angler.com/fish/225', 'max': 17.0},
	{'name': 'Mudcrab', 'url': 'http://en.ff14angler.com/fish/44', 'max': 12.4},
	{'name': 'Mudskipper', 'url': 'http://en.ff14angler.com/fish/27', 'max': 11.3},
	{'name': 'Mummer Wrasse', 'url': 'http://en.ff14angler.com/fish/133', 'max': 95.9},
	{'name': 'Mushroom Crab', 'url': 'http://en.ff14angler.com/fish/173', 'max': 25.4},
	{'name': 'Namitaro', 'url': 'http://en.ff14angler.com/fish/311', 'max': 234.1},
	{'name': 'Nautilus', 'url': 'http://en.ff14angler.com/fish/124', 'max': 55.0},
	{'name': 'Navigator\'s Brand', 'url': 'http://en.ff14angler.com/fish/216', 'max': 35.3},
	{'name': 'Navigator\'s Dagger', 'url': 'http://en.ff14angler.com/fish/38', 'max': 23.5},
	{'name': 'Ndendecki', 'url': 'http://en.ff14angler.com/fish/301', 'max': 194.7},
	{'name': 'Nepto Dragon', 'url': 'http://en.ff14angler.com/fish/290', 'max': 314.8},
	{'name': 'Ninja Betta', 'url': 'http://en.ff14angler.com/fish/297', 'max': 19.3},
	{'name': 'Noontide Oscar', 'url': 'http://en.ff14angler.com/fish/368', 'max': 29.4},
	{'name': 'Northern Pike', 'url': 'http://en.ff14angler.com/fish/122', 'max': 46.3},
	{'name': 'Nyctosaur', 'url': 'http://en.ff14angler.com/fish/454', 'max': 177.0},
	{'name': 'Oakroot', 'url': 'http://en.ff14angler.com/fish/118', 'max': 47.1},
	{'name': 'Ocean Cloud', 'url': 'http://en.ff14angler.com/fish/12', 'max': 10.9},
	{'name': 'Octomammoth', 'url': 'http://en.ff14angler.com/fish/230', 'max': 56.5},
	{'name': 'Ogre Barracuda', 'url': 'http://en.ff14angler.com/fish/58', 'max': 47.9},
	{'name': 'Ogre Horn Snail', 'url': 'http://en.ff14angler.com/fish/325', 'max': 11.7},
	{'name': 'Oil Eel', 'url': 'http://en.ff14angler.com/fish/415', 'max': 92.4},
	{'name': 'Old Hollow Eyes', 'url': 'http://en.ff14angler.com/fish/247', 'max': 25.2},
	{'name': 'Old Softie', 'url': 'http://en.ff14angler.com/fish/226', 'max': 12.8},
	{'name': 'Olgoi-Khorkhoi', 'url': 'http://en.ff14angler.com/fish/266', 'max': 121.1},
	{'name': 'Olpihant\'s Trunk', 'url': 'http://en.ff14angler.com/fish/458', 'max': 42.9},
	{'name': 'Orn Butterfly', 'url': 'http://en.ff14angler.com/fish/381', 'max': 21.7},
	{'name': 'Oschon\'s Print', 'url': 'http://en.ff14angler.com/fish/203', 'max': 20.5},
	{'name': 'Oven Catfish', 'url': 'http://en.ff14angler.com/fish/420', 'max': 145.5},
	{'name': 'Paglth\'an Discus', 'url': 'http://en.ff14angler.com/fish/140', 'max': 42.8},
	{'name': 'Pebble Crab', 'url': 'http://en.ff14angler.com/fish/26', 'max': 12.4},
	{'name': 'Philosopher\'s Stone', 'url': 'http://en.ff14angler.com/fish/390', 'max': 8.9},
	{'name': 'Piece of Blue Cloud Coral', 'url': 'http://en.ff14angler.com/fish/336', 'max': 38.8},
	{'name': 'Piece of Blue Coral', 'url': 'http://en.ff14angler.com/fish/57', 'max': 25.0},
	{'name': 'Piece of Cloud Coral', 'url': 'http://en.ff14angler.com/fish/315', 'max': 53.4},
	{'name': 'Piece of Gloaming Coral', 'url': 'http://en.ff14angler.com/fish/395', 'max': 64.8},
	{'name': 'Piece of Heavens Coral', 'url': 'http://en.ff14angler.com/fish/441', 'max': 64.7},
	{'name': 'Piece of Red Coral', 'url': 'http://en.ff14angler.com/fish/107', 'max': 35.3},
	{'name': 'Piece of White Coral', 'url': 'http://en.ff14angler.com/fish/10', 'max': 9.7},
	{'name': 'Pike Eel', 'url': 'http://en.ff14angler.com/fish/129', 'max': 79.0},
	{'name': 'Pipira', 'url': 'http://en.ff14angler.com/fish/16', 'max': 10.5},
	{'name': 'Pipira Pira', 'url': 'http://en.ff14angler.com/fish/341', 'max': 38.8},
	{'name': 'Pirarucu', 'url': 'http://en.ff14angler.com/fish/182', 'max': 106.1},
	{'name': 'Pirate\'s Bane', 'url': 'http://en.ff14angler.com/fish/300', 'max': 265.1},
	{'name': 'Plaguefish', 'url': 'http://en.ff14angler.com/fish/69', 'max': 16.8},
	{'name': 'Plaice', 'url': 'http://en.ff14angler.com/fish/138', 'max': 62.8},
	{'name': 'Platinum Fish', 'url': 'http://en.ff14angler.com/fish/376', 'max': 21.1},
	{'name': 'Pond Mussel', 'url': 'http://en.ff14angler.com/fish/50', 'max': 9.7},
	{'name': 'Poxpike', 'url': 'http://en.ff14angler.com/fish/175', 'max': 70.7},
	{'name': 'Priestfish', 'url': 'http://en.ff14angler.com/fish/456', 'max': 58.5},
	{'name': 'Princess Trout', 'url': 'http://en.ff14angler.com/fish/11', 'max': 9.7},
	{'name': 'Proto-Hropken', 'url': 'http://en.ff14angler.com/fish/401', 'max': 34.1},
	{'name': 'Pteranodon', 'url': 'http://en.ff14angler.com/fish/421', 'max': 177.0},
	{'name': 'Pterodactyl', 'url': 'http://en.ff14angler.com/fish/444', 'max': 216.4},
	{'name': 'Rainbow Trout', 'url': 'http://en.ff14angler.com/fish/28', 'max': 15.6},
	{'name': 'Raincaller', 'url': 'http://en.ff14angler.com/fish/117', 'max': 45.1},
	{'name': 'Razor Clam', 'url': 'http://en.ff14angler.com/fish/43', 'max': 12.4},
	{'name': 'Retribution Staff', 'url': 'http://en.ff14angler.com/fish/448', 'max': 98.3},
	{'name': 'Rhamphorhynchus', 'url': 'http://en.ff14angler.com/fish/168', 'max': 149.4},
	{'name': 'Rift Sailor', 'url': 'http://en.ff14angler.com/fish/142', 'max': 27.4},
	{'name': 'Rime Eater', 'url': 'http://en.ff14angler.com/fish/366', 'max': 74.3},
	{'name': 'River Crab', 'url': 'http://en.ff14angler.com/fish/29', 'max': 9.7},
	{'name': 'Rivet Oyster', 'url': 'http://en.ff14angler.com/fish/234', 'max': 14.6},
	{'name': 'Rock Lobster', 'url': 'http://en.ff14angler.com/fish/149', 'max': 31.3},
	{'name': 'Rock Mussel', 'url': 'http://en.ff14angler.com/fish/333', 'max': 6.1},
	{'name': 'Rockclimber', 'url': 'http://en.ff14angler.com/fish/411', 'max': 9.7},
	{'name': 'Root Skipper', 'url': 'http://en.ff14angler.com/fish/80', 'max': 10.9},
	{'name': 'Ropefish', 'url': 'http://en.ff14angler.com/fish/76', 'max': 38.0},
	{'name': 'Rothlyt Oyster', 'url': 'http://en.ff14angler.com/fish/35', 'max': 9.7},
	{'name': 'Rudderfish', 'url': 'http://en.ff14angler.com/fish/405', 'max': 74.7},
	{'name': 'Saber Sardine', 'url': 'http://en.ff14angler.com/fish/54', 'max': 31.7},
	{'name': 'Sabertooth Cod', 'url': 'http://en.ff14angler.com/fish/214', 'max': 24.1},
	{'name': 'Sagolii Monkfish', 'url': 'http://en.ff14angler.com/fish/147', 'max': 78.6},
	{'name': 'Sand Bream', 'url': 'http://en.ff14angler.com/fish/92', 'max': 21.9},
	{'name': 'Sandfish', 'url': 'http://en.ff14angler.com/fish/89', 'max': 13.2},
	{'name': 'Saucerfish', 'url': 'http://en.ff14angler.com/fish/148', 'max': 58.9},
	{'name': 'Scaleripper', 'url': 'http://en.ff14angler.com/fish/465', 'max': 298.5},
	{'name': 'Scholar Sculpin', 'url': 'http://en.ff14angler.com/fish/347', 'max': 21.9},
	{'name': 'Scorpionfly', 'url': 'http://en.ff14angler.com/fish/410', 'max': 31.3},
	{'name': 'Sea Bo', 'url': 'http://en.ff14angler.com/fish/62', 'max': 20.7},
	{'name': 'Sea Cucumber', 'url': 'http://en.ff14angler.com/fish/14', 'max': 9.3},
	{'name': 'Sea Devil', 'url': 'http://en.ff14angler.com/fish/143', 'max': 60.9},
	{'name': 'Sea Pickle', 'url': 'http://en.ff14angler.com/fish/72', 'max': 33.3},
	{'name': 'Seahag', 'url': 'http://en.ff14angler.com/fish/293', 'max': 223.1},
	{'name': 'Seema', 'url': 'http://en.ff14angler.com/fish/87', 'max': 36.9},
	{'name': 'Seema Patrician', 'url': 'http://en.ff14angler.com/fish/337', 'max': 38.4},
	{'name': 'Shadow Catfish', 'url': 'http://en.ff14angler.com/fish/64', 'max': 30.6},
	{'name': 'Shadowhisker', 'url': 'http://en.ff14angler.com/fish/369', 'max': 135.7},
	{'name': 'Shadowstreak', 'url': 'http://en.ff14angler.com/fish/283', 'max': 69.5},
	{'name': 'Shall Shell', 'url': 'http://en.ff14angler.com/fish/156', 'max': 82.5},
	{'name': 'Shark Tuna', 'url': 'http://en.ff14angler.com/fish/251', 'max': 103.8},
	{'name': 'Shipworm', 'url': 'http://en.ff14angler.com/fish/356', 'max': 39.2},
	{'name': 'Shonisaurus', 'url': 'http://en.ff14angler.com/fish/308', 'max': 274.7},
	{'name': 'Silver Shark', 'url': 'http://en.ff14angler.com/fish/111', 'max': 82.5},
	{'name': 'Silver Sovereign', 'url': 'http://en.ff14angler.com/fish/213', 'max': 175.8},
	{'name': 'Silverfish', 'url': 'http://en.ff14angler.com/fish/90', 'max': 16.4},
	{'name': 'Sky Faerie', 'url': 'http://en.ff14angler.com/fish/353', 'max': 9.3},
	{'name': 'Sky Sweeper', 'url': 'http://en.ff14angler.com/fish/385', 'max': 73.5},
	{'name': 'Skyfish', 'url': 'http://en.ff14angler.com/fish/132', 'max': 21.9},
	{'name': 'Skyworm', 'url': 'http://en.ff14angler.com/fish/317', 'max': 21.7},
	{'name': 'Slime King', 'url': 'http://en.ff14angler.com/fish/221', 'max': 13.4},
	{'name': 'Sludgeskipper', 'url': 'http://en.ff14angler.com/fish/131', 'max': 12.1},
	{'name': 'Snowcaller', 'url': 'http://en.ff14angler.com/fish/363', 'max': 92.0},
	{'name': 'Son of Levin', 'url': 'http://en.ff14angler.com/fish/272', 'max': 79.3},
	{'name': 'Sorcerer Fish', 'url': 'http://en.ff14angler.com/fish/326', 'max': 73.5},
	{'name': 'Southern Pike', 'url': 'http://en.ff14angler.com/fish/121', 'max': 46.3},
	{'name': 'Spearnose', 'url': 'http://en.ff14angler.com/fish/255', 'max': 43.0},
	{'name': 'Spotted Pleco', 'url': 'http://en.ff14angler.com/fish/73', 'max': 29.0},
	{'name': 'Spotted Puffer', 'url': 'http://en.ff14angler.com/fish/99', 'max': 5.8},
	{'name': 'Spring Urchin', 'url': 'http://en.ff14angler.com/fish/423', 'max': 13.0},
	{'name': 'Star Faerie', 'url': 'http://en.ff14angler.com/fish/394', 'max': 13.0},
	{'name': 'Starbright', 'url': 'http://en.ff14angler.com/fish/281', 'max': 74.3},
	{'name': 'Starflower', 'url': 'http://en.ff14angler.com/fish/323', 'max': 11.3},
	{'name': 'Steel Sky Pirate Spoil', 'url': 'http://en.ff14angler.com/fish/951', 'max': 11.4},
	{'name': 'Storm Chaser', 'url': 'http://en.ff14angler.com/fish/435', 'max': 153.4},
	{'name': 'Storm Core', 'url': 'http://en.ff14angler.com/fish/346', 'max': 34.8},
	{'name': 'Storm Rider', 'url': 'http://en.ff14angler.com/fish/102', 'max': 17.6},
	{'name': 'Stormdancer', 'url': 'http://en.ff14angler.com/fish/236', 'max': 67.8},
	{'name': 'Strip of Malm Kelp', 'url': 'http://en.ff14angler.com/fish/1', 'max': 8.9},
	{'name': 'Striped Goby', 'url': 'http://en.ff14angler.com/fish/6', 'max': 7.3},
	{'name': 'Stupendemys', 'url': 'http://en.ff14angler.com/fish/425', 'max': 162.4},
	{'name': 'Sundisc', 'url': 'http://en.ff14angler.com/fish/158', 'max': 51.0},
	{'name': 'Sunfish', 'url': 'http://en.ff14angler.com/fish/171', 'max': 97.9},
	{'name': 'Sunsail', 'url': 'http://en.ff14angler.com/fish/442', 'max': 25.6},
	{'name': 'Sweetfish', 'url': 'http://en.ff14angler.com/fish/380', 'max': 16.8},
	{'name': 'Sweetnewt', 'url': 'http://en.ff14angler.com/fish/259', 'max': 93.1},
	{'name': 'Syldra', 'url': 'http://en.ff14angler.com/fish/233', 'max': 51.8},
	{'name': 'Sylphsbane', 'url': 'http://en.ff14angler.com/fish/248', 'max': 60.6},
	{'name': 'Takitaro', 'url': 'http://en.ff14angler.com/fish/181', 'max': 94.3},
	{'name': 'Thaliak Caiman', 'url': 'http://en.ff14angler.com/fish/431', 'max': 181.0},
	{'name': 'The Assassin', 'url': 'http://en.ff14angler.com/fish/243', 'max': 14.6},
	{'name': 'The Captain\'s Chalice', 'url': 'http://en.ff14angler.com/fish/284', 'max': 86.7},
	{'name': 'The Dreamweaver', 'url': 'http://en.ff14angler.com/fish/466', 'max': 139.5},
	{'name': 'The Drowned Sniper', 'url': 'http://en.ff14angler.com/fish/274', 'max': 40.0},
	{'name': 'The Ewer King', 'url': 'http://en.ff14angler.com/fish/468', 'max': 119.6},
	{'name': 'The Gobfather', 'url': 'http://en.ff14angler.com/fish/258', 'max': 72.4},
	{'name': 'The Greatest Bream In The World', 'url': 'http://en.ff14angler.com/fish/245', 'max': 79.0},
	{'name': 'The Green Jester', 'url': 'http://en.ff14angler.com/fish/270', 'max': 51.1},
	{'name': 'The Grinner', 'url': 'http://en.ff14angler.com/fish/250', 'max': 60.7},
	{'name': 'The Impaler', 'url': 'http://en.ff14angler.com/fish/463', 'max': 22.2},
	{'name': 'The Lone Ripper', 'url': 'http://en.ff14angler.com/fish/262', 'max': 88.4},
	{'name': 'The Matriarch', 'url': 'http://en.ff14angler.com/fish/282', 'max': 8.7},
	{'name': 'The Old Man In The Sea', 'url': 'http://en.ff14angler.com/fish/289', 'max': 171.1},
	{'name': 'The Salter', 'url': 'http://en.ff14angler.com/fish/261', 'max': 8.7},
	{'name': 'The Second One', 'url': 'http://en.ff14angler.com/fish/472', 'max': 178.2},
	{'name': 'The Sinker', 'url': 'http://en.ff14angler.com/fish/257', 'max': 46.5},
	{'name': 'The Soul Of The Martyr', 'url': 'http://en.ff14angler.com/fish/470', 'max': 529.3},
	{'name': 'The Terpsichorean', 'url': 'http://en.ff14angler.com/fish/275', 'max': 32.9},
	{'name': 'The Thousand-Year Itch', 'url': 'http://en.ff14angler.com/fish/278', 'max': 69.5},
	{'name': 'The Warden\'s Wand', 'url': 'http://en.ff14angler.com/fish/254', 'max': 61.9},
	{'name': 'Thief Betta', 'url': 'http://en.ff14angler.com/fish/449', 'max': 12.0},
	{'name': 'Three-Lip Carp', 'url': 'http://en.ff14angler.com/fish/329', 'max': 72.7},
	{'name': 'Thunderbolt Eel', 'url': 'http://en.ff14angler.com/fish/428', 'max': 86.5},
	{'name': 'Thunderbolt Sculpin', 'url': 'http://en.ff14angler.com/fish/113', 'max': 37.3},
	{'name': 'Thundergut', 'url': 'http://en.ff14angler.com/fish/273', 'max': 55.8},
	{'name': 'Tiger Cod', 'url': 'http://en.ff14angler.com/fish/30', 'max': 16.0},
	{'name': 'Tigerfish', 'url': 'http://en.ff14angler.com/fish/352', 'max': 131.0},
	{'name': 'Timeworn Archaeoskin Map', 'url': 'http://en.ff14angler.com/fish/906', 'max': 11.6},
	{'name': 'Timeworn Boarskin Map', 'url': 'http://en.ff14angler.com/fish/904', 'max': 11.4},
	{'name': 'Timeworn Dragonskin Map', 'url': 'http://en.ff14angler.com/fish/908', 'max': 11.6},
	{'name': 'Timeworn Goatskin Map', 'url': 'http://en.ff14angler.com/fish/902', 'max': 11.4},
	{'name': 'Timeworn Leather Map', 'url': 'http://en.ff14angler.com/fish/901', 'max': 11.4},
	{'name': 'Timeworn Peisteskin Map', 'url': 'http://en.ff14angler.com/fish/905', 'max': 11.4},
	{'name': 'Timeworn Toadskin Map', 'url': 'http://en.ff14angler.com/fish/903', 'max': 11.4},
	{'name': 'Timeworn Wyvernskin Map', 'url': 'http://en.ff14angler.com/fish/907', 'max': 11.4},
	{'name': 'Tiny Axolotl', 'url': 'http://en.ff14angler.com/fish/374', 'max': 34.1},
	{'name': 'Tiny Tortoise', 'url': 'http://en.ff14angler.com/fish/185', 'max': 25.6},
	{'name': 'Titanic Sawfish', 'url': 'http://en.ff14angler.com/fish/180', 'max': 196.2},
	{'name': 'Toramafish', 'url': 'http://en.ff14angler.com/fish/241', 'max': 123.8},
	{'name': 'Tornado Shark', 'url': 'http://en.ff14angler.com/fish/398', 'max': 105.0},
	{'name': 'Trader Eel', 'url': 'http://en.ff14angler.com/fish/103', 'max': 41.2},
	{'name': 'Tri-Colored Carp', 'url': 'http://en.ff14angler.com/fish/46', 'max': 22.7},
	{'name': 'Tupuxuara', 'url': 'http://en.ff14angler.com/fish/433', 'max': 247.9},
	{'name': 'Twin-Tongued Carp', 'url': 'http://en.ff14angler.com/fish/480', 'max': 108.3},
	{'name': 'Twitchbeard', 'url': 'http://en.ff14angler.com/fish/253', 'max': 93.2},
	{'name': 'Unidentified Flying Biomass', 'url': 'http://en.ff14angler.com/fish/408', 'max': 26.1},
	{'name': 'Vampire Lampern', 'url': 'http://en.ff14angler.com/fish/150', 'max': 53.0},
	{'name': 'Vampiric Tapestry', 'url': 'http://en.ff14angler.com/fish/434', 'max': 139.2},
	{'name': 'Vanuhead', 'url': 'http://en.ff14angler.com/fish/349', 'max': 56.9},
	{'name': 'Velodyna Carp', 'url': 'http://en.ff14angler.com/fish/98', 'max': 40.4},
	{'name': 'Vidofnir', 'url': 'http://en.ff14angler.com/fish/469', 'max': 52.0},
	{'name': 'Vip Viper', 'url': 'http://en.ff14angler.com/fish/244', 'max': 38.2},
	{'name': 'Void Bass', 'url': 'http://en.ff14angler.com/fish/295', 'max': 91.1},
	{'name': 'Vongola Clam', 'url': 'http://en.ff14angler.com/fish/18', 'max': 6.9},
	{'name': 'Wahoo', 'url': 'http://en.ff14angler.com/fish/116', 'max': 60.9},
	{'name': 'Wandering Sculpin', 'url': 'http://en.ff14angler.com/fish/151', 'max': 42.8},
	{'name': 'Warballoon', 'url': 'http://en.ff14angler.com/fish/399', 'max': 83.7},
	{'name': 'Warmwater Bichir', 'url': 'http://en.ff14angler.com/fish/367', 'max': 77.7},
	{'name': 'Warmwater Trout', 'url': 'http://en.ff14angler.com/fish/51', 'max': 21.1},
	{'name': 'Weston Bowfin', 'url': 'http://en.ff14angler.com/fish/392', 'max': 42.8},
	{'name': 'Whilom Catfish', 'url': 'http://en.ff14angler.com/fish/321', 'max': 52.2},
	{'name': 'Whitelip Oyster', 'url': 'http://en.ff14angler.com/fish/88', 'max': 17.6},
	{'name': 'Whiteloom', 'url': 'http://en.ff14angler.com/fish/335', 'max': 30.6},
	{'name': 'Winged Gurnard', 'url': 'http://en.ff14angler.com/fish/422', 'max': 51.0},
	{'name': 'Wootz Knifefish', 'url': 'http://en.ff14angler.com/fish/162', 'max': 60.1},
	{'name': 'Wootz Knifefish Zenith', 'url': 'http://en.ff14angler.com/fish/303', 'max': 90.2},
	{'name': 'Worm of Nym', 'url': 'http://en.ff14angler.com/fish/252', 'max': 37.6},
	{'name': 'Yalm Lobster', 'url': 'http://en.ff14angler.com/fish/418', 'max': 53.0},
	{'name': 'Yugr\'am Salmon', 'url': 'http://en.ff14angler.com/fish/71', 'max': 31.0},
	{'name': 'Zalera', 'url': 'http://en.ff14angler.com/fish/201', 'max': 45.3},
        {'name': 'Thavnairian Leaf', 'url': 'http://ff14angler.com/fish/506', 'max': 34.5},
        {'name': 'Ghost Faerie', 'url': 'http://ff14angler.com/fish/507', 'max': 3.0},
        {'name': 'Piece of Red Sky Coral', 'url': 'http://ff14angler.com/fish/508', 'max': 64.8},
        {'name': 'Lovers\' Clam', 'url': 'http://ff14angler.com/fish/509', 'max': 8.9},
        {'name': 'River Shrimp', 'url': 'http://ff14angler.com/fish/510', 'max': 14.8},
        {'name': 'Peteinosaur', 'url': 'http://ff14angler.com/fish/510', 'max': 216.3}
]
