fishes = [
{"url": "http://ff14angler.com/fish/24", "max": 5.8, "available": "False", "name": "Abalathian Smelt", "index": 0},
{"url": "http://ff14angler.com/fish/34", "max": 6.9, "available": "True", "name": "Acorn Snail", "index": 1},
{"url": "http://ff14angler.com/fish/59", "max": 3.8, "available": "False", "name": "Aegis Shrimp", "index": 2},
{"url": "http://ff14angler.com/fish/377", "max": 18.4, "available": "True", "name": "Aether Eye", "index": 3},
{"url": "http://ff14angler.com/fish/287", "max": 32.3, "available": "False", "name": "Aetherlouse", "index": 4},
{"url": "http://ff14angler.com/fish/388", "max": 26.1, "available": "True", "name": "Aetherochemical Compound #123", "index": 5},
{"url": "http://ff14angler.com/fish/485", "max": 24.2, "available": "True", "name": "Aetherochemical Compound #666", "index": 6},
{"url": "http://ff14angler.com/fish/128", "max": 51.4, "available": "True", "name": "Agelyss Carp", "index": 7},
{"url": "http://ff14angler.com/fish/355", "max": 31.0, "available": "True", "name": "Aithon's Colt", "index": 8},
{"url": "http://ff14angler.com/fish/31", "max": 10.9, "available": "True", "name": "Ala Mhigan Fighting Fish", "index": 9},
{"url": "http://ff14angler.com/fish/396", "max": 9.2, "available": "False", "name": "Albino Octopus", "index": 10},
{"url": "http://ff14angler.com/fish/477", "max": 104.9, "available": "True", "name": "Allagan Bladeshark", "index": 11},
{"url": "http://ff14angler.com/fish/161", "max": 65.6, "available": "True", "name": "Alligator Garfish", "index": 12},
{"url": "http://ff14angler.com/fish/451", "max": 93.2, "available": "False", "name": "Amber Salamander", "index": 13},
{"url": "http://ff14angler.com/fish/338", "max": 29.8, "available": "True", "name": "Ammonite", "index": 14},
{"url": "http://ff14angler.com/fish/40", "max": 30.2, "available": "True", "name": "Angelfish", "index": 15},
{"url": "http://ff14angler.com/fish/145", "max": 54.2, "available": "True", "name": "Angry Pike", "index": 16},
{"url": "http://ff14angler.com/fish/285", "max": 41.1, "available": "True", "name": "Anomalocaris", "index": 17},
{"url": "http://ff14angler.com/fish/106", "max": 23.5, "available": "True", "name": "Antlion Slug", "index": 18},
{"url": "http://ff14angler.com/fish/474", "max": 445.9, "available": "False", "name": "Aphotic Pirarucu", "index": 19},
{"url": "http://ff14angler.com/fish/125", "max": 26.6, "available": "True", "name": "Archerfish", "index": 20},
{"url": "http://ff14angler.com/fish/460", "max": 62.0, "available": "True", "name": "Armored Catfish", "index": 21},
{"url": "http://ff14angler.com/fish/94", "max": 36.9, "available": "True", "name": "Armored Pleco", "index": 22},
{"url": "http://ff14angler.com/fish/210", "max": 48.9, "available": "False", "name": "Armorer", "index": 23},
{"url": "http://ff14angler.com/fish/77", "max": 69.1, "available": "False", "name": "Ash Tuna", "index": 24},
{"url": "http://ff14angler.com/fish/130", "max": 12.8, "available": "False", "name": "Assassin Betta", "index": 25},
{"url": "http://ff14angler.com/fish/473", "max": 46.7, "available": "False", "name": "Augmented High Allagan Helmet", "index": 26},
{"url": "http://ff14angler.com/fish/383", "max": 9.5, "available": "True", "name": "Autumn Leaf", "index": 27},
{"url": "http://ff14angler.com/fish/378", "max": 10.9, "available": "False", "name": "Azysfish", "index": 28},
{"url": "http://ff14angler.com/fish/97", "max": 48.7, "available": "False", "name": "Balloonfish", "index": 29},
{"url": "http://ff14angler.com/fish/427", "max": 97.5, "available": "False", "name": "Barreleye", "index": 30},
{"url": "http://ff14angler.com/fish/476", "max": 538.5, "available": "True", "name": "Basking Shark", "index": 31},
{"url": "http://ff14angler.com/fish/302", "max": 79.6, "available": "True", "name": "Bat-o'-Nine-Tails", "index": 32},
{"url": "http://ff14angler.com/fish/417", "max": 31.3, "available": "True", "name": "Battle Galley", "index": 33},
{"url": "http://ff14angler.com/fish/202", "max": 13.4, "available": "False", "name": "Beguiler Chub", "index": 34},
{"url": "http://ff14angler.com/fish/436", "max": 10.9, "available": "True", "name": "Berserker Betta", "index": 35},
{"url": "http://ff14angler.com/fish/65", "max": 52.6, "available": "True", "name": "Bianaq Bream", "index": 36},
{"url": "http://ff14angler.com/fish/55", "max": 25.4, "available": "False", "name": "Black Eel", "index": 37},
{"url": "http://ff14angler.com/fish/66", "max": 29.4, "available": "True", "name": "Black Ghost", "index": 38},
{"url": "http://ff14angler.com/fish/426", "max": 153.4, "available": "False", "name": "Black Magefish", "index": 39},
{"url": "http://ff14angler.com/fish/67", "max": 32.5, "available": "False", "name": "Black Sole", "index": 40},
{"url": "http://ff14angler.com/fish/120", "max": 21.5, "available": "False", "name": "Blacklip Oyster", "index": 41},
{"url": "http://ff14angler.com/fish/137", "max": 58.9, "available": "True", "name": "Blind Manta", "index": 42},
{"url": "http://ff14angler.com/fish/25", "max": 8.1, "available": "False", "name": "Blindfish", "index": 43},
{"url": "http://ff14angler.com/fish/312", "max": 61.9, "available": "True", "name": "Blood Red Bonytongue", "index": 44},
{"url": "http://ff14angler.com/fish/412", "max": 18.4, "available": "False", "name": "Blood Skipper", "index": 45},
{"url": "http://ff14angler.com/fish/271", "max": 56.0, "available": "True", "name": "Bloodbath", "index": 46},
{"url": "http://ff14angler.com/fish/219", "max": 15.8, "available": "True", "name": "Bloody Brewer", "index": 47},
{"url": "http://ff14angler.com/fish/49", "max": 21.5, "available": "True", "name": "Blowfish", "index": 48},
{"url": "http://ff14angler.com/fish/306", "max": 64.1, "available": "False", "name": "Blue Corpse", "index": 49},
{"url": "http://ff14angler.com/fish/371", "max": 60.5, "available": "True", "name": "Blue Medusa", "index": 50},
{"url": "http://ff14angler.com/fish/45", "max": 37.6, "available": "True", "name": "Blue Octopus", "index": 51},
{"url": "http://ff14angler.com/fish/222", "max": 26.3, "available": "True", "name": "Blue Widow", "index": 52},
{"url": "http://ff14angler.com/fish/42", "max": 17.6, "available": "False", "name": "Bluebell Salmon", "index": 53},
{"url": "http://ff14angler.com/fish/322", "max": 25.4, "available": "False", "name": "Blueclaw Shrimp", "index": 54},
{"url": "http://ff14angler.com/fish/487", "max": 156.0, "available": "True", "name": "Bobgoblin Bass", "index": 55},
{"url": "http://ff14angler.com/fish/135", "max": 53.0, "available": "True", "name": "Boltfish", "index": 56},
{"url": "http://ff14angler.com/fish/406", "max": 90.5, "available": "False", "name": "Bomb Puffer", "index": 57},
{"url": "http://ff14angler.com/fish/260", "max": 73.1, "available": "True", "name": "Bombardfish", "index": 58},
{"url": "http://ff14angler.com/fish/79", "max": 15.2, "available": "True", "name": "Bone Cleaner", "index": 59},
{"url": "http://ff14angler.com/fish/9", "max": 8.5, "available": "False", "name": "Bone Crayfish", "index": 60},
{"url": "http://ff14angler.com/fish/82", "max": 41.2, "available": "True", "name": "Bonytongue", "index": 61},
{"url": "http://ff14angler.com/fish/177", "max": 56.9, "available": "True", "name": "Bowfin", "index": 62},
{"url": "http://ff14angler.com/fish/141", "max": 45.5, "available": "False", "name": "Boxing Pleco", "index": 63},
{"url": "http://ff14angler.com/fish/21", "max": 8.9, "available": "False", "name": "Brass Loach", "index": 64},
{"url": "http://ff14angler.com/fish/108", "max": 48.7, "available": "True", "name": "Bronze Lake Trout", "index": 65},
{"url": "http://ff14angler.com/fish/389", "max": 70.2, "available": "True", "name": "Brown Bolo", "index": 66},
{"url": "http://ff14angler.com/fish/339", "max": 18.4, "available": "False", "name": "Bubble Eye", "index": 67},
{"url": "http://ff14angler.com/fish/330", "max": 12.5, "available": "True", "name": "Bullfrog", "index": 68},
{"url": "http://ff14angler.com/fish/373", "max": 14.0, "available": "False", "name": "Bullwhip", "index": 69},
{"url": "http://ff14angler.com/fish/334", "max": 10.9, "available": "True", "name": "Buoyant Oviform", "index": 70},
{"url": "http://ff14angler.com/fish/167", "max": 77.4, "available": "True", "name": "Cadaver Carp", "index": 71},
{"url": "http://ff14angler.com/fish/402", "max": 121.9, "available": "True", "name": "Caiman", "index": 72},
{"url": "http://ff14angler.com/fish/298", "max": 127.4, "available": "True", "name": "Canavan", "index": 73},
{"url": "http://ff14angler.com/fish/437", "max": 9.7, "available": "False", "name": "Capelin", "index": 74},
{"url": "http://ff14angler.com/fish/164", "max": 86.5, "available": "False", "name": "Caravan Eel", "index": 75},
{"url": "http://ff14angler.com/fish/224", "max": 19.9, "available": "False", "name": "Carp Diem", "index": 76},
{"url": "http://ff14angler.com/fish/204", "max": 14.0, "available": "True", "name": "Caterwauler", "index": 77},
{"url": "http://ff14angler.com/fish/429", "max": 247.9, "available": "True", "name": "Catkiller", "index": 78},
{"url": "http://ff14angler.com/fish/153", "max": 32.9, "available": "False", "name": "Cave Cherax", "index": 79},
{"url": "http://ff14angler.com/fish/269", "max": 15.1, "available": "False", "name": "Charon's Lantern", "index": 80},
{"url": "http://ff14angler.com/fish/424", "max": 25.2, "available": "True", "name": "Cherry Trout", "index": 81},
{"url": "http://ff14angler.com/fish/228", "max": 26.4, "available": "True", "name": "Chirurgeon", "index": 82},
{"url": "http://ff14angler.com/fish/3", "max": 8.9, "available": "False", "name": "Chub", "index": 83},
{"url": "http://ff14angler.com/fish/372", "max": 38.7, "available": "False", "name": "Cindersmith", "index": 84},
{"url": "http://ff14angler.com/fish/483", "max": 186.9, "available": "True", "name": "Cirrostratus", "index": 85},
{"url": "http://ff14angler.com/fish/63", "max": 17.2, "available": "True", "name": "Climbing Perch", "index": 86},
{"url": "http://ff14angler.com/fish/134", "max": 28.6, "available": "True", "name": "Cloud Cutter", "index": 87},
{"url": "http://ff14angler.com/fish/126", "max": 17.6, "available": "False", "name": "Cloud Jellyfish", "index": 88},
{"url": "http://ff14angler.com/fish/360", "max": 38.0, "available": "False", "name": "Cloud Rider", "index": 89},
{"url": "http://ff14angler.com/fish/331", "max": 6.9, "available": "True", "name": "Cloudfish", "index": 90},
{"url": "http://ff14angler.com/fish/91", "max": 34.1, "available": "True", "name": "Clown Loach", "index": 91},
{"url": "http://ff14angler.com/fish/413", "max": 95.5, "available": "True", "name": "Cobrafish", "index": 92},
{"url": "http://ff14angler.com/fish/439", "max": 3.0, "available": "True", "name": "Coerthan Clione", "index": 93},
{"url": "http://ff14angler.com/fish/318", "max": 12.4, "available": "True", "name": "Coerthan Crab", "index": 94},
{"url": "http://ff14angler.com/fish/457", "max": 12.4, "available": "False", "name": "Coerthan Oyster", "index": 95},
{"url": "http://ff14angler.com/fish/362", "max": 5.0, "available": "True", "name": "Coerthan Puffer", "index": 96},
{"url": "http://ff14angler.com/fish/154", "max": 82.5, "available": "True", "name": "Coeurlfish", "index": 97},
{"url": "http://ff14angler.com/fish/166", "max": 80.6, "available": "True", "name": "Coelacanth", "index": 98},
{"url": "http://ff14angler.com/fish/291", "max": 108.8, "available": "False", "name": "Coelacanthus", "index": 99},
{"url": "http://ff14angler.com/fish/387", "max": 65.6, "available": "False", "name": "Cometoise", "index": 100},
{"url": "http://ff14angler.com/fish/119", "max": 17.6, "available": "True", "name": "Common Sculpin", "index": 101},
{"url": "http://ff14angler.com/fish/41", "max": 11.7, "available": "True", "name": "Copperfish", "index": 102},
{"url": "http://ff14angler.com/fish/20", "max": 13.2, "available": "False", "name": "Coral Butterfly", "index": 103},
{"url": "http://ff14angler.com/fish/296", "max": 68.4, "available": "True", "name": "Cornelia", "index": 104},
{"url": "http://ff14angler.com/fish/2", "max": 6.9, "available": "False", "name": "Crayfish", "index": 105},
{"url": "http://ff14angler.com/fish/17", "max": 10.1, "available": "False", "name": "Crimson Crayfish", "index": 106},
{"url": "http://ff14angler.com/fish/104", "max": 38.0, "available": "False", "name": "Crimson Trout", "index": 107},
{"url": "http://ff14angler.com/fish/447", "max": 29.1, "available": "False", "name": "Crown Trout", "index": 108},
{"url": "http://ff14angler.com/fish/205", "max": 37.1, "available": "False", "name": "Crystal Perch", "index": 109},
{"url": "http://ff14angler.com/fish/379", "max": 15.2, "available": "False", "name": "Crystalfin", "index": 110},
{"url": "http://ff14angler.com/fish/238", "max": 29.4, "available": "True", "name": "Cupfish", "index": 111},
{"url": "http://ff14angler.com/fish/268", "max": 55.2, "available": "False", "name": "Daniffen's Mark", "index": 112},
{"url": "http://ff14angler.com/fish/217", "max": 17.0, "available": "False", "name": "Dark Ambusher", "index": 113},
{"url": "http://ff14angler.com/fish/56", "max": 27.4, "available": "False", "name": "Dark Bass", "index": 114},
{"url": "http://ff14angler.com/fish/212", "max": 41.2, "available": "False", "name": "Dark Knight", "index": 115},
{"url": "http://ff14angler.com/fish/36", "max": 11.3, "available": "False", "name": "Dark Sleeper", "index": 116},
{"url": "http://ff14angler.com/fish/305", "max": 81.2, "available": "False", "name": "Darkstar", "index": 117},
{"url": "http://ff14angler.com/fish/280", "max": 57.1, "available": "False", "name": "Dawn Maiden", "index": 118},
{"url": "http://ff14angler.com/fish/96", "max": 31.3, "available": "False", "name": "Desert Catfish", "index": 119},
{"url": "http://ff14angler.com/fish/475", "max": 230.1, "available": "False", "name": "Dimorphodon", "index": 120},
{"url": "http://ff14angler.com/fish/172", "max": 165.2, "available": "False", "name": "Dinichthys", "index": 121},
{"url": "http://ff14angler.com/fish/246", "max": 64.7, "available": "True", "name": "Dirty Herry", "index": 122},
{"url": "http://ff14angler.com/fish/264", "max": 64.2, "available": "True", "name": "Discobolus", "index": 123},
{"url": "http://ff14angler.com/fish/105", "max": 34.5, "available": "True", "name": "Discus", "index": 124},
{"url": "http://ff14angler.com/fish/397", "max": 26.2, "available": "False", "name": "Dragon's Soul", "index": 125},
{"url": "http://ff14angler.com/fish/364", "max": 34.1, "available": "True", "name": "Dragonhead", "index": 126},
{"url": "http://ff14angler.com/fish/361", "max": 104.2, "available": "False", "name": "Dravanian Bass", "index": 127},
{"url": "http://ff14angler.com/fish/440", "max": 9.7, "available": "False", "name": "Dravanian Smelt", "index": 128},
{"url": "http://ff14angler.com/fish/342", "max": 18.0, "available": "True", "name": "Dravanian Squeaker", "index": 129},
{"url": "http://ff14angler.com/fish/215", "max": 12.3, "available": "False", "name": "Dream Goby", "index": 130},
{"url": "http://ff14angler.com/fish/110", "max": 55.0, "available": "True", "name": "Dune Manta", "index": 131},
{"url": "http://ff14angler.com/fish/13", "max": 8.1, "available": "False", "name": "Dusk Goby", "index": 132},
{"url": "http://ff14angler.com/fish/100", "max": 28.2, "available": "True", "name": "Dustfish", "index": 133},
{"url": "http://ff14angler.com/fish/7", "max": 9.3, "available": "True", "name": "Dwarf Catfish", "index": 134},
{"url": "http://ff14angler.com/fish/176", "max": 60.9, "available": "True", "name": "Emperor Fish", "index": 135},
{"url": "http://ff14angler.com/fish/292", "max": 283.2, "available": "True", "name": "Endoceras", "index": 136},
{"url": "http://ff14angler.com/fish/403", "max": 251.8, "available": "True", "name": "Euphotic Pirarucu", "index": 137},
{"url": "http://ff14angler.com/fish/47", "max": 17.6, "available": "True", "name": "Eunuch Crayfish", "index": 138},
{"url": "http://ff14angler.com/fish/445", "max": 272.5, "available": "False", "name": "Eurhinosaur", "index": 139},
{"url": "http://ff14angler.com/fish/33", "max": 17.6, "available": "True", "name": "Faerie Bass", "index": 140},
{"url": "http://ff14angler.com/fish/220", "max": 26.4, "available": "False", "name": "Faerie Queen", "index": 141},
{"url": "http://ff14angler.com/fish/114", "max": 40.4, "available": "True", "name": "Fall Jumper", "index": 142},
{"url": "http://ff14angler.com/fish/319", "max": 23.1, "available": "False", "name": "Fanged Clam", "index": 143},
{"url": "http://ff14angler.com/fish/462", "max": 8.6, "available": "False", "name": "Fat Purse", "index": 144},
{"url": "http://ff14angler.com/fish/8", "max": 8.5, "available": "False", "name": "Finger Shrimp", "index": 145},
{"url": "http://ff14angler.com/fish/242", "max": 47.0, "available": "False", "name": "Fingers", "index": 146},
{"url": "http://ff14angler.com/fish/60", "max": 7.7, "available": "False", "name": "Five-Ilm Pleco", "index": 147},
{"url": "http://ff14angler.com/fish/479", "max": 95.2, "available": "True", "name": "Flarefish", "index": 148},
{"url": "http://ff14angler.com/fish/453", "max": 126.9, "available": "False", "name": "Fleece Stingray", "index": 149},
{"url": "http://ff14angler.com/fish/249", "max": 25.8, "available": "True", "name": "Floating Boulder", "index": 150},
{"url": "http://ff14angler.com/fish/400", "max": 139.3, "available": "False", "name": "Fossiltongue", "index": 151},
{"url": "http://ff14angler.com/fish/391", "max": 53.0, "available": "True", "name": "Fountfish", "index": 152},
{"url": "http://ff14angler.com/fish/53", "max": 18.0, "available": "True", "name": "Four-Eyed Fish", "index": 153},
{"url": "http://ff14angler.com/fish/286", "max": 141.6, "available": "True", "name": "Frilled Shark", "index": 154},
{"url": "http://ff14angler.com/fish/83", "max": 21.5, "available": "False", "name": "Fullmoon Sardine", "index": 155},
{"url": "http://ff14angler.com/fish/438", "max": 36.1, "available": "True", "name": "Functional Proto-Hropken", "index": 156},
{"url": "http://ff14angler.com/fish/136", "max": 58.9, "available": "True", "name": "Garpike", "index": 157},
{"url": "http://ff14angler.com/fish/446", "max": 15.6, "available": "False", "name": "Gem Marimo", "index": 158},
{"url": "http://ff14angler.com/fish/223", "max": 34.1, "available": "True", "name": "Ghost Carp", "index": 159},
{"url": "http://ff14angler.com/fish/95", "max": 43.2, "available": "True", "name": "Giant Bass", "index": 160},
{"url": "http://ff14angler.com/fish/163", "max": 70.3, "available": "True", "name": "Giant Catfish", "index": 161},
{"url": "http://ff14angler.com/fish/157", "max": 57.7, "available": "False", "name": "Giant Donko", "index": 162},
{"url": "http://ff14angler.com/fish/169", "max": 117.6, "available": "True", "name": "Giant Squid", "index": 163},
{"url": "http://ff14angler.com/fish/310", "max": 141.6, "available": "True", "name": "Giant Takitaro", "index": 164},
{"url": "http://ff14angler.com/fish/313", "max": 139.4, "available": "False", "name": "Gigant Clam", "index": 165},
{"url": "http://ff14angler.com/fish/348", "max": 109.3, "available": "False", "name": "Gigant Grouper", "index": 166},
{"url": "http://ff14angler.com/fish/170", "max": 149.5, "available": "True", "name": "Gigant Octopus", "index": 167},
{"url": "http://ff14angler.com/fish/186", "max": 25.6, "available": "False", "name": "Gigantpole", "index": 168},
{"url": "http://ff14angler.com/fish/209", "max": 123.9, "available": "True", "name": "Gigantshark", "index": 169},
{"url": "http://ff14angler.com/fish/324", "max": 35.3, "available": "True", "name": "Glacier Core", "index": 170},
{"url": "http://ff14angler.com/fish/52", "max": 24.7, "available": "True", "name": "Glass Perch", "index": 171},
{"url": "http://ff14angler.com/fish/237", "max": 17.6, "available": "False", "name": "Glimmerscale", "index": 172},
{"url": "http://ff14angler.com/fish/452", "max": 8.9, "available": "True", "name": "Gnomefish", "index": 173},
{"url": "http://ff14angler.com/fish/370", "max": 52.2, "available": "False", "name": "Gobbie Mask", "index": 174},
{"url": "http://ff14angler.com/fish/443", "max": 104.2, "available": "False", "name": "Goblin Bass", "index": 175},
{"url": "http://ff14angler.com/fish/127", "max": 48.3, "available": "True", "name": "Goblin Perch", "index": 176},
{"url": "http://ff14angler.com/fish/101", "max": 41.6, "available": "True", "name": "Golden Loach", "index": 177},
{"url": "http://ff14angler.com/fish/208", "max": 19.9, "available": "True", "name": "Goldenfin", "index": 178},
{"url": "http://ff14angler.com/fish/146", "max": 21.1, "available": "False", "name": "Goldfish", "index": 179},
{"url": "http://ff14angler.com/fish/450", "max": 13.4, "available": "True", "name": "Goldsmith Crab", "index": 180},
{"url": "http://ff14angler.com/fish/152", "max": 97.5, "available": "False", "name": "Goosefish", "index": 181},
{"url": "http://ff14angler.com/fish/354", "max": 27.0, "available": "False", "name": "Granite Crab", "index": 182},
{"url": "http://ff14angler.com/fish/340", "max": 82.5, "available": "True", "name": "Grass Carp", "index": 183},
{"url": "http://en.ff14angler.com/fish/211", "max": 14.6, "available": "True", "name": "Great Gudgeon", "index": 184},
{"url": "http://en.ff14angler.com/fish/78", "max": 8.9, "available": "False", "name": "Grip Killifish", "index": 185},
{"url": "http://en.ff14angler.com/fish/19", "max": 9.7, "available": "True", "name": "Gudgeon", "index": 186},
{"url": "http://en.ff14angler.com/fish/478", "max": 96.6, "available": "False", "name": "Hailfinder", "index": 187},
{"url": "http://en.ff14angler.com/fish/160", "max": 100.2, "available": "True", "name": "Halibut", "index": 188},
{"url": "http://en.ff14angler.com/fish/70", "max": 58.9, "available": "False", "name": "Hammerhead Shark", "index": 189},
{"url": "http://en.ff14angler.com/fish/279", "max": 98.5, "available": "True", "name": "Hannibal", "index": 190},
{"url": "http://en.ff14angler.com/fish/85", "max": 53.0, "available": "True", "name": "Haraldr Haddock", "index": 191},
{"url": "http://en.ff14angler.com/fish/15", "max": 12.8, "available": "False", "name": "Harbor Herring", "index": 192},
{"url": "http://en.ff14angler.com/fish/357", "max": 4.6, "available": "True", "name": "Hedgemole Cricket", "index": 193},
{"url": "http://en.ff14angler.com/fish/304", "max": 228.7, "available": "False", "name": "Helicoprion", "index": 194},
{"url": "http://en.ff14angler.com/fish/178", "max": 87.1, "available": "True", "name": "Heliobatis", "index": 195},
{"url": "http://en.ff14angler.com/fish/32", "max": 17.2, "available": "True", "name": "Helmet Crab", "index": 196},
{"url": "http://en.ff14angler.com/fish/277", "max": 146.9, "available": "False", "name": "Helmsman's Hand", "index": 197},
{"url": "http://en.ff14angler.com/fish/375", "max": 27.4, "available": "False", "name": "High Allagan Helmet", "index": 198},
{"url": "http://en.ff14angler.com/fish/232", "max": 27.6, "available": "True", "name": "High Perch", "index": 199},
{"url": "http://en.ff14angler.com/fish/419", "max": 66.4, "available": "True", "name": "Hinterlands Perch", "index": 200},
{"url": "http://en.ff14angler.com/fish/409", "max": 4.6, "available": "True", "name": "Hospitalier Fish", "index": 201},
{"url": "http://en.ff14angler.com/fish/327", "max": 65.6, "available": "False", "name": "Hotrod", "index": 202},
{"url": "http://en.ff14angler.com/fish/484", "max": 33.5, "available": "True", "name": "Hraesvelgr's Tear", "index": 203},
{"url": "http://en.ff14angler.com/fish/382", "max": 44.5, "available": "True", "name": "Hundred Fin", "index": 204},
{"url": "http://en.ff14angler.com/fish/486", "max": 34.0, "available": "True", "name": "Hundred-Eyed Axolotl", "index": 205},
{"url": "http://en.ff14angler.com/fish/316", "max": 3.0, "available": "True", "name": "Ice Faerie", "index": 206},
{"url": "http://en.ff14angler.com/fish/314", "max": 12.1, "available": "False", "name": "Icepick", "index": 207},
{"url": "http://en.ff14angler.com/fish/294", "max": 8.7, "available": "True", "name": "Ignus Horn", "index": 208},
{"url": "http://en.ff14angler.com/fish/109", "max": 5.8, "available": "True", "name": "Ignus Snail", "index": 209},
{"url": "http://en.ff14angler.com/fish/404", "max": 93.9, "available": "False", "name": "Illuminati Perch", "index": 210},
{"url": "http://en.ff14angler.com/fish/139", "max": 60.9, "available": "False", "name": "Ilsabardian Bass", "index": 211},
{"url": "http://en.ff14angler.com/fish/288", "max": 31.7, "available": "True", "name": "Imperial Goldfish", "index": 212},
{"url": "http://en.ff14angler.com/fish/75", "max": 43.2, "available": "False", "name": "Indigo Herring", "index": 213},
{"url": "http://en.ff14angler.com/fish/471", "max": 34.1, "available": "False", "name": "Inkfish", "index": 214},
{"url": "http://en.ff14angler.com/fish/265", "max": 57.1, "available": "False", "name": "Iron Noose", "index": 215},
{"url": "http://en.ff14angler.com/fish/235", "max": 18.7, "available": "True", "name": "Jacques the Snipper", "index": 216},
{"url": "http://en.ff14angler.com/fish/48", "max": 25.0, "available": "True", "name": "Jade Eel", "index": 217},
{"url": "http://en.ff14angler.com/fish/416", "max": 82.5, "available": "True", "name": "Jeweled Jellyfish", "index": 218},
{"url": "http://en.ff14angler.com/fish/240", "max": 31.7, "available": "False", "name": "Joan of Trout", "index": 219},
{"url": "http://en.ff14angler.com/fish/218", "max": 56.0, "available": "False", "name": "Judgeray", "index": 220},
{"url": "http://en.ff14angler.com/fish/174", "max": 53.0, "available": "True", "name": "Judgment Staff", "index": 221},
{"url": "http://en.ff14angler.com/fish/184", "max": 62.4, "available": "True", "name": "Jungle Catfish", "index": 222},
{"url": "http://en.ff14angler.com/fish/207", "max": 146.3, "available": "True", "name": "Junkmonger", "index": 223},
{"url": "http://en.ff14angler.com/fish/263", "max": 72.9, "available": "True", "name": "King of the Spring", "index": 224},
{"url": "http://en.ff14angler.com/fish/343", "max": 25.4, "available": "False", "name": "Kissing Fish", "index": 225},
{"url": "http://en.ff14angler.com/fish/144", "max": 49.5, "available": "False", "name": "Kissing Trout", "index": 226},
{"url": "http://en.ff14angler.com/fish/115", "max": 43.6, "available": "False", "name": "Knifefish", "index": 227},
{"url": "http://en.ff14angler.com/fish/123", "max": 6.9, "available": "True", "name": "Kobold Puffer", "index": 228},
{"url": "http://en.ff14angler.com/fish/299", "max": 208.2, "available": "True", "name": "Kuno the Killer", "index": 229},
{"url": "http://en.ff14angler.com/fish/37", "max": 18.4, "available": "True", "name": "La Noscean Perch", "index": 230},
{"url": "http://en.ff14angler.com/fish/464", "max": 56.5, "available": "False", "name": "La Reale", "index": 231},
{"url": "http://en.ff14angler.com/fish/320", "max": 9.1, "available": "False", "name": "Lake Urchin", "index": 232},
{"url": "http://en.ff14angler.com/fish/74", "max": 10.1, "available": "False", "name": "Lamp Marimo", "index": 233},
{"url": "http://en.ff14angler.com/fish/68", "max": 28.6, "available": "True", "name": "Lamprey", "index": 234},
{"url": "http://en.ff14angler.com/fish/345", "max": 34.5, "available": "True", "name": "Lava Crab", "index": 235},
{"url": "http://en.ff14angler.com/fish/455", "max": 6.9, "available": "False", "name": "Lava Snail", "index": 236},
{"url": "http://en.ff14angler.com/fish/432", "max": 214.7, "available": "True", "name": "Lavalord", "index": 237},
{"url": "http://en.ff14angler.com/fish/93", "max": 60.9, "available": "False", "name": "Lavender Remora", "index": 238},
{"url": "http://en.ff14angler.com/fish/81", "max": 34.5, "available": "False", "name": "Leafy Seadragon", "index": 239},
{"url": "http://en.ff14angler.com/fish/393", "max": 78.2, "available": "False", "name": "Letter Puffer", "index": 240},
{"url": "http://en.ff14angler.com/fish/256", "max": 43.3, "available": "False", "name": "Levinlight", "index": 241},
{"url": "http://en.ff14angler.com/fish/155", "max": 118.0, "available": "True", "name": "Little Thalaos", "index": 242},
{"url": "http://en.ff14angler.com/fish/5", "max": 8.1, "available": "True", "name": "Lominsan Anchovy", "index": 243},
{"url": "http://en.ff14angler.com/fish/430", "max": 259.6, "available": "True", "name": "Loosetongue", "index": 244},
{"url": "http://en.ff14angler.com/fish/112", "max": 46.3, "available": "True", "name": "Loyal Pleco", "index": 245},
{"url": "http://en.ff14angler.com/fish/351", "max": 60.5, "available": "True", "name": "Lungfish", "index": 246},
{"url": "http://en.ff14angler.com/fish/481", "max": 23.8, "available": "True", "name": "Madam Butterfly", "index": 247},
{"url": "http://en.ff14angler.com/fish/461", "max": 9.9, "available": "True", "name": "Magic Bucket", "index": 248},
{"url": "http://en.ff14angler.com/fish/267", "max": 86.7, "available": "True", "name": "Magic Carpet", "index": 249},
{"url": "http://en.ff14angler.com/fish/309", "max": 38.2, "available": "True", "name": "Magicked Mushroom", "index": 250},
{"url": "http://en.ff14angler.com/fish/386", "max": 51.8, "available": "False", "name": "Magma Louse", "index": 251},
{"url": "http://en.ff14angler.com/fish/359", "max": 47.9, "available": "True", "name": "Magma Tree", "index": 252},
{"url": "http://en.ff14angler.com/fish/307", "max": 201.8, "available": "True", "name": "Mahar", "index": 253},
{"url": "http://en.ff14angler.com/fish/159", "max": 97.5, "available": "False", "name": "Mahi-Mahi", "index": 254},
{"url": "http://en.ff14angler.com/fish/332", "max": 19.5, "available": "True", "name": "Mahu Wai", "index": 255},
{"url": "http://en.ff14angler.com/fish/328", "max": 43.2, "available": "True", "name": "Maiboi", "index": 256},
{"url": "http://en.ff14angler.com/fish/23", "max": 11.7, "available": "True", "name": "Maiden Carp", "index": 257},
{"url": "http://en.ff14angler.com/fish/384", "max": 25.8, "available": "True", "name": "Manasail", "index": 258},
{"url": "http://en.ff14angler.com/fish/350", "max": 26.6, "available": "False", "name": "Marble Oscar", "index": 259},
{"url": "http://en.ff14angler.com/fish/227", "max": 22.9, "available": "True", "name": "Marrow Sucker", "index": 260},
{"url": "http://en.ff14angler.com/fish/231", "max": 17.6, "available": "True", "name": "Matron Carp", "index": 261},
{"url": "http://en.ff14angler.com/fish/165", "max": 114.0, "available": "False", "name": "Mazlaya Marlin", "index": 262},
{"url": "http://en.ff14angler.com/fish/179", "max": 181.0, "available": "True", "name": "Megalodon", "index": 263},
{"url": "http://en.ff14angler.com/fish/488", "max": 117.5, "available": "False", "name": "Merciless", "index": 264},
{"url": "http://en.ff14angler.com/fish/365", "max": 90.4, "available": "False", "name": "Mercy Staff", "index": 265},
{"url": "http://en.ff14angler.com/fish/4", "max": 9.3, "available": "False", "name": "Merlthor Goby", "index": 266},
{"url": "http://en.ff14angler.com/fish/239", "max": 25.8, "available": "True", "name": "Meteor Survivor", "index": 267},
{"url": "http://en.ff14angler.com/fish/467", "max": 118.0, "available": "True", "name": "Meteortoise", "index": 268},
{"url": "http://en.ff14angler.com/fish/276", "max": 24.7, "available": "True", "name": "Mirrorscale", "index": 269},
{"url": "http://en.ff14angler.com/fish/344", "max": 47.9, "available": "False", "name": "Mitre Slug", "index": 270},
{"url": "http://en.ff14angler.com/fish/84", "max": 21.9, "available": "False", "name": "Mitten Crab", "index": 271},
{"url": "http://en.ff14angler.com/fish/39", "max": 13.2, "available": "True", "name": "Moat Carp", "index": 272},
{"url": "http://en.ff14angler.com/fish/482", "max": 15.6, "available": "True", "name": "Moggle Mogpom", "index": 273},
{"url": "http://en.ff14angler.com/fish/358", "max": 11.7, "available": "False", "name": "Mogpom", "index": 274},
{"url": "http://en.ff14angler.com/fish/206", "max": 16.4, "available": "True", "name": "Moldva", "index": 275},
{"url": "http://en.ff14angler.com/fish/86", "max": 37.3, "available": "False", "name": "Monke Onke", "index": 276},
{"url": "http://en.ff14angler.com/fish/61", "max": 58.5, "available": "False", "name": "Monkfish", "index": 277},
{"url": "http://en.ff14angler.com/fish/414", "max": 127.0, "available": "True", "name": "Moogle Spirit", "index": 278},
{"url": "http://en.ff14angler.com/fish/22", "max": 16.3, "available": "True", "name": "Moraby Flounder", "index": 279},
{"url": "http://en.ff14angler.com/fish/183", "max": 94.3, "available": "True", "name": "Morinabaligi", "index": 280},
{"url": "http://en.ff14angler.com/fish/459", "max": 117.6, "available": "True", "name": "Mountain Kraken", "index": 281},
{"url": "http://en.ff14angler.com/fish/407", "max": 72.7, "available": "True", "name": "Mucous Minnow", "index": 282},
{"url": "http://en.ff14angler.com/fish/229", "max": 18.7, "available": "False", "name": "Mud Golem", "index": 283},
{"url": "http://en.ff14angler.com/fish/225", "max": 17.0, "available": "False", "name": "Mud Pulgrim", "index": 284},
{"url": "http://en.ff14angler.com/fish/44", "max": 12.4, "available": "True", "name": "Mudcrab", "index": 285},
{"url": "http://en.ff14angler.com/fish/27", "max": 11.3, "available": "True", "name": "Mudskipper", "index": 286},
{"url": "http://en.ff14angler.com/fish/133", "max": 95.9, "available": "True", "name": "Mummer Wrasse", "index": 287},
{"url": "http://en.ff14angler.com/fish/173", "max": 25.4, "available": "False", "name": "Mushroom Crab", "index": 288},
{"url": "http://en.ff14angler.com/fish/311", "max": 234.1, "available": "True", "name": "Namitaro", "index": 289},
{"url": "http://en.ff14angler.com/fish/124", "max": 55.0, "available": "False", "name": "Nautilus", "index": 290},
{"url": "http://en.ff14angler.com/fish/216", "max": 35.3, "available": "False", "name": "Navigator's Brand", "index": 291},
{"url": "http://en.ff14angler.com/fish/38", "max": 23.5, "available": "True", "name": "Navigator's Dagger", "index": 292},
{"url": "http://en.ff14angler.com/fish/301", "max": 194.7, "available": "True", "name": "Ndendecki", "index": 293},
{"url": "http://en.ff14angler.com/fish/290", "max": 314.8, "available": "True", "name": "Nepto Dragon", "index": 294},
{"url": "http://en.ff14angler.com/fish/297", "max": 19.3, "available": "False", "name": "Ninja Betta", "index": 295},
{"url": "http://en.ff14angler.com/fish/368", "max": 29.4, "available": "True", "name": "Noontide Oscar", "index": 296},
{"url": "http://en.ff14angler.com/fish/122", "max": 46.3, "available": "False", "name": "Northern Pike", "index": 297},
{"url": "http://en.ff14angler.com/fish/454", "max": 177.0, "available": "True", "name": "Nyctosaur", "index": 298},
{"url": "http://en.ff14angler.com/fish/118", "max": 47.1, "available": "True", "name": "Oakroot", "index": 299},
{"url": "http://en.ff14angler.com/fish/12", "max": 10.9, "available": "False", "name": "Ocean Cloud", "index": 300},
{"url": "http://en.ff14angler.com/fish/230", "max": 56.5, "available": "False", "name": "Octomammoth", "index": 301},
{"url": "http://en.ff14angler.com/fish/58", "max": 47.9, "available": "False", "name": "Ogre Barracuda", "index": 302},
{"url": "http://en.ff14angler.com/fish/325", "max": 11.7, "available": "True", "name": "Ogre Horn Snail", "index": 303},
{"url": "http://en.ff14angler.com/fish/415", "max": 92.4, "available": "True", "name": "Oil Eel", "index": 304},
{"url": "http://en.ff14angler.com/fish/247", "max": 25.2, "available": "True", "name": "Old Hollow Eyes", "index": 305},
{"url": "http://en.ff14angler.com/fish/226", "max": 12.8, "available": "True", "name": "Old Softie", "index": 306},
{"url": "http://en.ff14angler.com/fish/266", "max": 121.1, "available": "True", "name": "Olgoi-Khorkhoi", "index": 307},
{"url": "http://en.ff14angler.com/fish/458", "max": 42.9, "available": "False", "name": "Olpihant's Trunk", "index": 308},
{"url": "http://en.ff14angler.com/fish/381", "max": 21.7, "available": "False", "name": "Orn Butterfly", "index": 309},
{"url": "http://en.ff14angler.com/fish/203", "max": 20.5, "available": "True", "name": "Oschon's Print", "index": 310},
{"url": "http://en.ff14angler.com/fish/420", "max": 145.5, "available": "False", "name": "Oven Catfish", "index": 311},
{"url": "http://en.ff14angler.com/fish/140", "max": 42.8, "available": "False", "name": "Paglth'an Discus", "index": 312},
{"url": "http://en.ff14angler.com/fish/26", "max": 12.4, "available": "False", "name": "Pebble Crab", "index": 313},
{"url": "http://en.ff14angler.com/fish/390", "max": 8.9, "available": "True", "name": "Philosopher's Stone", "index": 314},
{"url": "http://en.ff14angler.com/fish/336", "max": 38.8, "available": "True", "name": "Piece of Blue Cloud Coral", "index": 315},
{"url": "http://en.ff14angler.com/fish/57", "max": 25.0, "available": "True", "name": "Piece of Blue Coral", "index": 316},
{"url": "http://en.ff14angler.com/fish/315", "max": 53.4, "available": "False", "name": "Piece of Cloud Coral", "index": 317},
{"url": "http://en.ff14angler.com/fish/395", "max": 64.8, "available": "True", "name": "Piece of Gloaming Coral", "index": 318},
{"url": "http://en.ff14angler.com/fish/441", "max": 64.7, "available": "False", "name": "Piece of Heavens Coral", "index": 319},
{"url": "http://en.ff14angler.com/fish/107", "max": 35.3, "available": "True", "name": "Piece of Red Coral", "index": 320},
{"url": "http://en.ff14angler.com/fish/10", "max": 9.7, "available": "False", "name": "Piece of White Coral", "index": 321},
{"url": "http://en.ff14angler.com/fish/129", "max": 79.0, "available": "False", "name": "Pike Eel", "index": 322},
{"url": "http://en.ff14angler.com/fish/16", "max": 10.5, "available": "False", "name": "Pipira", "index": 323},
{"url": "http://en.ff14angler.com/fish/341", "max": 38.8, "available": "False", "name": "Pipira Pira", "index": 324},
{"url": "http://en.ff14angler.com/fish/182", "max": 106.1, "available": "False", "name": "Pirarucu", "index": 325},
{"url": "http://en.ff14angler.com/fish/300", "max": 265.1, "available": "False", "name": "Pirate's Bane", "index": 326},
{"url": "http://en.ff14angler.com/fish/69", "max": 16.8, "available": "True", "name": "Plaguefish", "index": 327},
{"url": "http://en.ff14angler.com/fish/138", "max": 62.8, "available": "True", "name": "Plaice", "index": 328},
{"url": "http://en.ff14angler.com/fish/376", "max": 21.1, "available": "False", "name": "Platinum Fish", "index": 329},
{"url": "http://en.ff14angler.com/fish/50", "max": 9.7, "available": "False", "name": "Pond Mussel", "index": 330},
{"url": "http://en.ff14angler.com/fish/175", "max": 70.7, "available": "False", "name": "Poxpike", "index": 331},
{"url": "http://en.ff14angler.com/fish/456", "max": 58.5, "available": "False", "name": "Priestfish", "index": 332},
{"url": "http://en.ff14angler.com/fish/11", "max": 9.7, "available": "False", "name": "Princess Trout", "index": 333},
{"url": "http://en.ff14angler.com/fish/401", "max": 34.1, "available": "False", "name": "Proto-Hropken", "index": 334},
{"url": "http://en.ff14angler.com/fish/421", "max": 177.0, "available": "False", "name": "Pteranodon", "index": 335},
{"url": "http://en.ff14angler.com/fish/444", "max": 216.4, "available": "False", "name": "Pterodactyl", "index": 336},
{"url": "http://en.ff14angler.com/fish/28", "max": 15.6, "available": "True", "name": "Rainbow Trout", "index": 337},
{"url": "http://en.ff14angler.com/fish/117", "max": 45.1, "available": "True", "name": "Raincaller", "index": 338},
{"url": "http://en.ff14angler.com/fish/43", "max": 12.4, "available": "True", "name": "Razor Clam", "index": 339},
{"url": "http://en.ff14angler.com/fish/448", "max": 98.3, "available": "False", "name": "Retribution Staff", "index": 340},
{"url": "http://en.ff14angler.com/fish/168", "max": 149.4, "available": "True", "name": "Rhamphorhynchus", "index": 341},
{"url": "http://en.ff14angler.com/fish/142", "max": 27.4, "available": "True", "name": "Rift Sailor", "index": 342},
{"url": "http://en.ff14angler.com/fish/366", "max": 74.3, "available": "False", "name": "Rime Eater", "index": 343},
{"url": "http://en.ff14angler.com/fish/29", "max": 9.7, "available": "True", "name": "River Crab", "index": 344},
{"url": "http://en.ff14angler.com/fish/234", "max": 14.6, "available": "False", "name": "Rivet Oyster", "index": 345},
{"url": "http://en.ff14angler.com/fish/149", "max": 31.3, "available": "False", "name": "Rock Lobster", "index": 346},
{"url": "http://en.ff14angler.com/fish/333", "max": 6.1, "available": "False", "name": "Rock Mussel", "index": 347},
{"url": "http://en.ff14angler.com/fish/411", "max": 9.7, "available": "False", "name": "Rockclimber", "index": 348},
{"url": "http://en.ff14angler.com/fish/80", "max": 10.9, "available": "True", "name": "Root Skipper", "index": 349},
{"url": "http://en.ff14angler.com/fish/76", "max": 38.0, "available": "False", "name": "Ropefish", "index": 350},
{"url": "http://en.ff14angler.com/fish/35", "max": 9.7, "available": "True", "name": "Rothlyt Oyster", "index": 351},
{"url": "http://en.ff14angler.com/fish/405", "max": 74.7, "available": "False", "name": "Rudderfish", "index": 352},
{"url": "http://en.ff14angler.com/fish/54", "max": 31.7, "available": "False", "name": "Saber Sardine", "index": 353},
{"url": "http://en.ff14angler.com/fish/214", "max": 24.1, "available": "False", "name": "Sabertooth Cod", "index": 354},
{"url": "http://en.ff14angler.com/fish/147", "max": 78.6, "available": "False", "name": "Sagolii Monkfish", "index": 355},
{"url": "http://en.ff14angler.com/fish/92", "max": 21.9, "available": "False", "name": "Sand Bream", "index": 356},
{"url": "http://en.ff14angler.com/fish/89", "max": 13.2, "available": "True", "name": "Sandfish", "index": 357},
{"url": "http://en.ff14angler.com/fish/148", "max": 58.9, "available": "True", "name": "Saucerfish", "index": 358},
{"url": "http://en.ff14angler.com/fish/465", "max": 298.5, "available": "False", "name": "Scaleripper", "index": 359},
{"url": "http://en.ff14angler.com/fish/347", "max": 21.9, "available": "False", "name": "Scholar Sculpin", "index": 360},
{"url": "http://en.ff14angler.com/fish/410", "max": 31.3, "available": "True", "name": "Scorpionfly", "index": 361},
{"url": "http://en.ff14angler.com/fish/62", "max": 20.7, "available": "True", "name": "Sea Bo", "index": 362},
{"url": "http://en.ff14angler.com/fish/14", "max": 9.3, "available": "False", "name": "Sea Cucumber", "index": 363},
{"url": "http://en.ff14angler.com/fish/143", "max": 60.9, "available": "False", "name": "Sea Devil", "index": 364},
{"url": "http://en.ff14angler.com/fish/72", "max": 33.3, "available": "False", "name": "Sea Pickle", "index": 365},
{"url": "http://en.ff14angler.com/fish/293", "max": 223.1, "available": "False", "name": "Seahag", "index": 366},
{"url": "http://en.ff14angler.com/fish/87", "max": 36.9, "available": "True", "name": "Seema", "index": 367},
{"url": "http://en.ff14angler.com/fish/337", "max": 38.4, "available": "True", "name": "Seema Patrician", "index": 368},
{"url": "http://en.ff14angler.com/fish/64", "max": 30.6, "available": "True", "name": "Shadow Catfish", "index": 369},
{"url": "http://en.ff14angler.com/fish/369", "max": 135.7, "available": "True", "name": "Shadowhisker", "index": 370},
{"url": "http://en.ff14angler.com/fish/283", "max": 69.5, "available": "True", "name": "Shadowstreak", "index": 371},
{"url": "http://en.ff14angler.com/fish/156", "max": 82.5, "available": "True", "name": "Shall Shell", "index": 372},
{"url": "http://en.ff14angler.com/fish/251", "max": 103.8, "available": "True", "name": "Shark Tuna", "index": 373},
{"url": "http://en.ff14angler.com/fish/356", "max": 39.2, "available": "True", "name": "Shipworm", "index": 374},
{"url": "http://en.ff14angler.com/fish/308", "max": 274.7, "available": "True", "name": "Shonisaurus", "index": 375},
{"url": "http://en.ff14angler.com/fish/111", "max": 82.5, "available": "False", "name": "Silver Shark", "index": 376},
{"url": "http://en.ff14angler.com/fish/213", "max": 175.8, "available": "True", "name": "Silver Sovereign", "index": 377},
{"url": "http://en.ff14angler.com/fish/90", "max": 16.4, "available": "False", "name": "Silverfish", "index": 378},
{"url": "http://en.ff14angler.com/fish/353", "max": 9.3, "available": "True", "name": "Sky Faerie", "index": 379},
{"url": "http://en.ff14angler.com/fish/385", "max": 73.5, "available": "False", "name": "Sky Sweeper", "index": 380},
{"url": "http://en.ff14angler.com/fish/132", "max": 21.9, "available": "False", "name": "Skyfish", "index": 381},
{"url": "http://en.ff14angler.com/fish/317", "max": 21.7, "available": "True", "name": "Skyworm", "index": 382},
{"url": "http://en.ff14angler.com/fish/221", "max": 13.4, "available": "False", "name": "Slime King", "index": 383},
{"url": "http://en.ff14angler.com/fish/131", "max": 12.1, "available": "True", "name": "Sludgeskipper", "index": 384},
{"url": "http://en.ff14angler.com/fish/363", "max": 92.0, "available": "False", "name": "Snowcaller", "index": 385},
{"url": "http://en.ff14angler.com/fish/272", "max": 79.3, "available": "False", "name": "Son of Levin", "index": 386},
{"url": "http://en.ff14angler.com/fish/326", "max": 73.5, "available": "False", "name": "Sorcerer Fish", "index": 387},
{"url": "http://en.ff14angler.com/fish/121", "max": 46.3, "available": "True", "name": "Southern Pike", "index": 388},
{"url": "http://en.ff14angler.com/fish/255", "max": 43.0, "available": "True", "name": "Spearnose", "index": 389},
{"url": "http://en.ff14angler.com/fish/73", "max": 29.0, "available": "False", "name": "Spotted Pleco", "index": 390},
{"url": "http://en.ff14angler.com/fish/99", "max": 5.8, "available": "False", "name": "Spotted Puffer", "index": 391},
{"url": "http://en.ff14angler.com/fish/423", "max": 13.0, "available": "True", "name": "Spring Urchin", "index": 392},
{"url": "http://en.ff14angler.com/fish/394", "max": 13.0, "available": "True", "name": "Star Faerie", "index": 393},
{"url": "http://en.ff14angler.com/fish/281", "max": 74.3, "available": "False", "name": "Starbright", "index": 394},
{"url": "http://en.ff14angler.com/fish/323", "max": 11.3, "available": "False", "name": "Starflower", "index": 395},
{"url": "http://en.ff14angler.com/fish/951", "max": 11.4, "available": "False", "name": "Steel Sky Pirate Spoil", "index": 396},
{"url": "http://en.ff14angler.com/fish/435", "max": 153.4, "available": "True", "name": "Storm Chaser", "index": 397},
{"url": "http://en.ff14angler.com/fish/346", "max": 34.8, "available": "False", "name": "Storm Core", "index": 398},
{"url": "http://en.ff14angler.com/fish/102", "max": 17.6, "available": "True", "name": "Storm Rider", "index": 399},
{"url": "http://en.ff14angler.com/fish/236", "max": 67.8, "available": "False", "name": "Stormdancer", "index": 400},
{"url": "http://en.ff14angler.com/fish/1", "max": 8.9, "available": "False", "name": "Strip of Malm Kelp", "index": 401},
{"url": "http://en.ff14angler.com/fish/6", "max": 7.3, "available": "True", "name": "Striped Goby", "index": 402},
{"url": "http://en.ff14angler.com/fish/425", "max": 162.4, "available": "False", "name": "Stupendemys", "index": 403},
{"url": "http://en.ff14angler.com/fish/158", "max": 51.0, "available": "False", "name": "Sundisc", "index": 404},
{"url": "http://en.ff14angler.com/fish/171", "max": 97.9, "available": "False", "name": "Sunfish", "index": 405},
{"url": "http://en.ff14angler.com/fish/442", "max": 25.6, "available": "True", "name": "Sunsail", "index": 406},
{"url": "http://en.ff14angler.com/fish/380", "max": 16.8, "available": "False", "name": "Sweetfish", "index": 407},
{"url": "http://en.ff14angler.com/fish/259", "max": 93.1, "available": "False", "name": "Sweetnewt", "index": 408},
{"url": "http://en.ff14angler.com/fish/233", "max": 51.8, "available": "True", "name": "Syldra", "index": 409},
{"url": "http://en.ff14angler.com/fish/248", "max": 60.6, "available": "False", "name": "Sylphsbane", "index": 410},
{"url": "http://en.ff14angler.com/fish/181", "max": 94.3, "available": "True", "name": "Takitaro", "index": 411},
{"url": "http://en.ff14angler.com/fish/431", "max": 181.0, "available": "False", "name": "Thaliak Caiman", "index": 412},
{"url": "http://en.ff14angler.com/fish/243", "max": 14.6, "available": "False", "name": "The Assassin", "index": 413},
{"url": "http://en.ff14angler.com/fish/284", "max": 86.7, "available": "True", "name": "The Captain's Chalice", "index": 414},
{"url": "http://en.ff14angler.com/fish/466", "max": 139.5, "available": "True", "name": "The Dreamweaver", "index": 415},
{"url": "http://en.ff14angler.com/fish/274", "max": 40.0, "available": "True", "name": "The Drowned Sniper", "index": 416},
{"url": "http://en.ff14angler.com/fish/468", "max": 119.6, "available": "True", "name": "The Ewer King", "index": 417},
{"url": "http://en.ff14angler.com/fish/258", "max": 72.4, "available": "True", "name": "The Gobfather", "index": 418},
{"url": "http://en.ff14angler.com/fish/245", "max": 79.0, "available": "True", "name": "The Greatest Bream In The World", "index": 419},
{"url": "http://en.ff14angler.com/fish/270", "max": 51.1, "available": "True", "name": "The Green Jester", "index": 420},
{"url": "http://en.ff14angler.com/fish/250", "max": 60.7, "available": "False", "name": "The Grinner", "index": 421},
{"url": "http://en.ff14angler.com/fish/463", "max": 22.2, "available": "False", "name": "The Impaler", "index": 422},
{"url": "http://en.ff14angler.com/fish/262", "max": 88.4, "available": "False", "name": "The Lone Ripper", "index": 423},
{"url": "http://en.ff14angler.com/fish/282", "max": 8.7, "available": "True", "name": "The Matriarch", "index": 424},
{"url": "http://en.ff14angler.com/fish/289", "max": 171.1, "available": "True", "name": "The Old Man In The Sea", "index": 425},
{"url": "http://en.ff14angler.com/fish/261", "max": 8.7, "available": "True", "name": "The Salter", "index": 426},
{"url": "http://en.ff14angler.com/fish/472", "max": 178.2, "available": "True", "name": "The Second One", "index": 427},
{"url": "http://en.ff14angler.com/fish/257", "max": 46.5, "available": "False", "name": "The Sinker", "index": 428},
{"url": "http://en.ff14angler.com/fish/470", "max": 529.3, "available": "True", "name": "The Soul Of The Martyr", "index": 429},
{"url": "http://en.ff14angler.com/fish/275", "max": 32.9, "available": "False", "name": "The Terpsichorean", "index": 430},
{"url": "http://en.ff14angler.com/fish/278", "max": 69.5, "available": "False", "name": "The Thousand-Year Itch", "index": 431},
{"url": "http://en.ff14angler.com/fish/254", "max": 61.9, "available": "False", "name": "The Warden's Wand", "index": 432},
{"url": "http://en.ff14angler.com/fish/449", "max": 12.0, "available": "True", "name": "Thief Betta", "index": 433},
{"url": "http://en.ff14angler.com/fish/329", "max": 72.7, "available": "False", "name": "Three-Lip Carp", "index": 434},
{"url": "http://en.ff14angler.com/fish/428", "max": 86.5, "available": "True", "name": "Thunderbolt Eel", "index": 435},
{"url": "http://en.ff14angler.com/fish/113", "max": 37.3, "available": "True", "name": "Thunderbolt Sculpin", "index": 436},
{"url": "http://en.ff14angler.com/fish/273", "max": 55.8, "available": "False", "name": "Thundergut", "index": 437},
{"url": "http://en.ff14angler.com/fish/30", "max": 16.0, "available": "True", "name": "Tiger Cod", "index": 438},
{"url": "http://en.ff14angler.com/fish/352", "max": 131.0, "available": "True", "name": "Tigerfish", "index": 439},
{"url": "http://en.ff14angler.com/fish/906", "max": 11.6, "available": "False", "name": "Timeworn Archaeoskin Map", "index": 440},
{"url": "http://en.ff14angler.com/fish/904", "max": 11.4, "available": "False", "name": "Timeworn Boarskin Map", "index": 441},
{"url": "http://en.ff14angler.com/fish/908", "max": 11.6, "available": "False", "name": "Timeworn Dragonskin Map", "index": 442},
{"url": "http://en.ff14angler.com/fish/902", "max": 11.4, "available": "True", "name": "Timeworn Goatskin Map", "index": 443},
{"url": "http://en.ff14angler.com/fish/901", "max": 11.4, "available": "False", "name": "Timeworn Leather Map", "index": 444},
{"url": "http://en.ff14angler.com/fish/905", "max": 11.4, "available": "True", "name": "Timeworn Peisteskin Map", "index": 445},
{"url": "http://en.ff14angler.com/fish/903", "max": 11.4, "available": "False", "name": "Timeworn Toadskin Map", "index": 446},
{"url": "http://en.ff14angler.com/fish/907", "max": 11.4, "available": "True", "name": "Timeworn Wyvernskin Map", "index": 447},
{"url": "http://en.ff14angler.com/fish/374", "max": 34.1, "available": "True", "name": "Tiny Axolotl", "index": 448},
{"url": "http://en.ff14angler.com/fish/185", "max": 25.6, "available": "True", "name": "Tiny Tortoise", "index": 449},
{"url": "http://en.ff14angler.com/fish/180", "max": 196.2, "available": "False", "name": "Titanic Sawfish", "index": 450},
{"url": "http://en.ff14angler.com/fish/241", "max": 123.8, "available": "False", "name": "Toramafish", "index": 451},
{"url": "http://en.ff14angler.com/fish/398", "max": 105.0, "available": "False", "name": "Tornado Shark", "index": 452},
{"url": "http://en.ff14angler.com/fish/103", "max": 41.2, "available": "False", "name": "Trader Eel", "index": 453},
{"url": "http://en.ff14angler.com/fish/46", "max": 22.7, "available": "False", "name": "Tri-Colored Carp", "index": 454},
{"url": "http://en.ff14angler.com/fish/433", "max": 247.9, "available": "True", "name": "Tupuxuara", "index": 455},
{"url": "http://en.ff14angler.com/fish/480", "max": 108.3, "available": "False", "name": "Twin-Tongued Carp", "index": 456},
{"url": "http://en.ff14angler.com/fish/253", "max": 93.2, "available": "False", "name": "Twitchbeard", "index": 457},
{"url": "http://en.ff14angler.com/fish/408", "max": 26.1, "available": "True", "name": "Unidentified Flying Biomass", "index": 458},
{"url": "http://en.ff14angler.com/fish/150", "max": 53.0, "available": "False", "name": "Vampire Lampern", "index": 459},
{"url": "http://en.ff14angler.com/fish/434", "max": 139.2, "available": "True", "name": "Vampiric Tapestry", "index": 460},
{"url": "http://en.ff14angler.com/fish/349", "max": 56.9, "available": "True", "name": "Vanuhead", "index": 461},
{"url": "http://en.ff14angler.com/fish/98", "max": 40.4, "available": "True", "name": "Velodyna Carp", "index": 462},
{"url": "http://en.ff14angler.com/fish/469", "max": 52.0, "available": "False", "name": "Vidofnir", "index": 463},
{"url": "http://en.ff14angler.com/fish/244", "max": 38.2, "available": "True", "name": "Vip Viper", "index": 464},
{"url": "http://en.ff14angler.com/fish/295", "max": 91.1, "available": "True", "name": "Void Bass", "index": 465},
{"url": "http://en.ff14angler.com/fish/18", "max": 6.9, "available": "True", "name": "Vongola Clam", "index": 466},
{"url": "http://en.ff14angler.com/fish/116", "max": 60.9, "available": "True", "name": "Wahoo", "index": 467},
{"url": "http://en.ff14angler.com/fish/151", "max": 42.8, "available": "True", "name": "Wandering Sculpin", "index": 468},
{"url": "http://en.ff14angler.com/fish/399", "max": 83.7, "available": "False", "name": "Warballoon", "index": 469},
{"url": "http://en.ff14angler.com/fish/367", "max": 77.7, "available": "True", "name": "Warmwater Bichir", "index": 470},
{"url": "http://en.ff14angler.com/fish/51", "max": 21.1, "available": "False", "name": "Warmwater Trout", "index": 471},
{"url": "http://en.ff14angler.com/fish/392", "max": 42.8, "available": "True", "name": "Weston Bowfin", "index": 472},
{"url": "http://en.ff14angler.com/fish/321", "max": 52.2, "available": "True", "name": "Whilom Catfish", "index": 473},
{"url": "http://en.ff14angler.com/fish/88", "max": 17.6, "available": "False", "name": "Whitelip Oyster", "index": 474},
{"url": "http://en.ff14angler.com/fish/335", "max": 30.6, "available": "True", "name": "Whiteloom", "index": 475},
{"url": "http://en.ff14angler.com/fish/422", "max": 51.0, "available": "False", "name": "Winged Gurnard", "index": 476},
{"url": "http://en.ff14angler.com/fish/162", "max": 60.1, "available": "False", "name": "Wootz Knifefish", "index": 477},
{"url": "http://en.ff14angler.com/fish/303", "max": 90.2, "available": "False", "name": "Wootz Knifefish Zenith", "index": 478},
{"url": "http://en.ff14angler.com/fish/252", "max": 37.6, "available": "False", "name": "Worm of Nym", "index": 479},
{"url": "http://en.ff14angler.com/fish/418", "max": 53.0, "available": "True", "name": "Yalm Lobster", "index": 480},
{"url": "http://en.ff14angler.com/fish/71", "max": 31.0, "available": "True", "name": "Yugr'am Salmon", "index": 481},
{"url": "http://en.ff14angler.com/fish/201", "max": 45.3, "available": "True", "name": "Zalera", "index": 482},
{"url": "http://ff14angler.com/fish/506", "max": 34.5, "available": "True", "name": "Thavnairian Leaf", "index": 483},
{"url": "http://ff14angler.com/fish/507", "max": 3.0, "available": "False", "name": "Ghost Faerie", "index": 484},
{"url": "http://ff14angler.com/fish/508", "max": 64.8, "available": "True", "name": "Piece of Red Sky Coral", "index": 485},
{"url": "http://ff14angler.com/fish/509", "max": 8.9, "available": "False", "name": "Lovers' Clam", "index": 486},
{"url": "http://ff14angler.com/fish/510", "max": 14.8, "available": "False", "name": "River Shrimp", "index": 487},
{"url": "http://ff14angler.com/fish/511", "max": 216.3, "available": "False", "name": "Peteinosaur", "index": 488}
]